vespa-engine/sample-apps

Vagrantfile

@geirst please review
Caveat: now requires vagrant-vbguest plugin installed for mounting
to work as expected when doing vagrant up.

Use vanilla CentOS 7 box in Vagrantfile

---

.travis.yml
README.md

FYI @tokle 
Do not merge yet. Requires that _6-SNAPSHOT_ is not used as version for Vespa dependencies.

Build on Travis-CI

---

basic-search-java/pom.xml

with https://github.com/vespa-engine/vespa/issues/3479 the sample apps should use container, not container-dev - lets try basic search first, compiles and run unit tests - the doc tests will fail if this breaks - @gjoranv or @bratseth please merge

use container - #3479

---

basic-search-java/pom.xml
basic-search-tensor/pom.xml
blog-recommendation/pom.xml
boolean-search/pom.xml
http-api-using-request-handlers-and-processors/pom.xml
http-api-using-searcher/pom.xml

Let the pom update itself upon building. This means that the user will from time to time have one build with outdated vespa_version, but the next build will use the latest release. 
NOTE: the user will get unstaged changes preventing git pull after the version has auto-updated. But the alternative is a gradually more outdated version until the user runs git pull manually.
FYI: @frodelu, @bratseth

Update dependency versions in the 'validate' phase.

---

basic-search-java/pom.xml
basic-search-tensor/pom.xml
blog-recommendation/pom.xml
boolean-search/pom.xml
http-api-using-request-handlers-and-processors/pom.xml
http-api-using-searcher/pom.xml

Reverts parts of #33, which was sent a bit late on a Friday afternoon
An application should never be built on a newer vespa version than it will be running on. Always upgrade vespa on the runtime system before upgrading the vespa deps on the build system.
You can always run the version update manually with `mvn versions:update-properties`

Revert "Update dependency versions in the 'validate' phase."

---

blog-recommendation/README.md

Fixed documentation test because HTML parser expect `&` to be an escape character.

Fix blog recommentation doc test

---

basic-search-tensor/src/main/application/search/query-profiles/default.xml

@lesters please review
Not strictly needed here because you set the tensor programmatically so the type is derived from the value, but makes things easier to build on.

Set default query profile type

---

boolean-search/README.md

Fixes broken documentation testing. Vespa commands need to be run within the Docker container.
@aressem Please review.
@bjorncs FYI.

Feed boolean-search from within Docker container

---

blog-recommendation/src/main/java/com/yahoo/example/UserProfileSearcher.java

Searchers which modify the query tree constructed from input YQL statements need to be annotated to work as expected (see: https://docs.vespa.ai/documentation/reference/query-language-reference.html).
Just let me know if there's anything else I need to address here.

Add annotation due to modification of YQL query tree

---

basic-search-on-docker-swarm/src/main/application/services.xml

Note that the id will be 'container' when that is used as tag name.

Replace deprecated 'jdisc' with 'container'

---

basic-search-on-docker-swarm/src/main/application/services.xml
basic-search-tensor/src/main/application/services.xml

* Best practice to avoid implicit id that depends on xml tag name.

Add explicit id for container clusters

---

album-recommendation-java/src/main/application/deployment.xml

`<notifications>` element is not supported on Vespa Cloud, so removing it from sample-app we use for Cloud until it is supported.

Remove notifications from deployment.xml

---

vespa-cloud/vespa-documentation-search/src/main/application/searchdefinitions/doc.sd

- as documents will be separated in the index by the namespace feature in the ID - this is hence a better name

will migrate to using namespace

---

vespa-cloud/cord-19-search/blacklist.txt
vespa-cloud/cord-19-search/scripts/add-citation-data.py
vespa-cloud/cord-19-search/scripts/compute-inbound-citations.py

@jobergum please review and merge. Still hacking away at the citation extraction. Seems the scite dataset does case-sensitive DOI matching, while the doi.org ignores case, and so they miss some references. 
The bib_entries also have journal appended to title for quite a few refs, so this lets the longest title which is a prefix of a bib_entry item  count as a match

More small fixes

---

vespa-cloud/cord-19-search/blacklist.txt
vespa-cloud/cord-19-search/scripts/add-citation-data.py
vespa-cloud/cord-19-search/scripts/compute-inbound-citations.py

@jobergum please review and merge.
Seems the extra matches from longest prefix match was mostly attributed to matches like `influenza` or similar, for titles like `influenza bla bla bla bla bla bla bla bla ... more bla` — clearly not correct.

Let refs point to all duplicates of a title, and do not collapse these

---

vespa-cloud/cord-19-search/src/main/application/search/query-profiles/types/root.xml
vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd
vespa-cloud/cord-19-search/src/main/application/services.xml
vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedPaperSearcherANN.java

Examples
/search/?query=%2Brelated_to:612 %2Bschools
Will do approximate nearest neighboor search using title embedding vector from article 612 and include 'schools's as a matching term. Ranking is done by related-ann-with-matching which is a combination of rawScore(embedding vector) and Vespa's nativeRank. 
Searcher triggers on &id=x, or presence of related_to IntItem in the query (Which is removed before hitting the backend)

Implement related_to:id

---

vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd

Freshness will use "now" as the highest time by default, so
articles dated in the future will all sort the same.

Sort dates in the future correctly

---

vespa-cloud/cord-19-search/src/main/application/search/query-profiles/types/root.xml
vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd

With the 2020-04-10 cord-19 dataset we also got something they call SPECTER paper embeddings, 768 dimensional embedding. https://github.com/allenai/paper-embedding-public-apis

Add new embedding released with 2020-04-10 dataset

---

vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd
vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedArticlesByNNSearcher.java
vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/RelatedArticlesByNNSearcherTest.java

Last CORD-19 dataset release contained SPECTER embeddings for all articles, the embeddings have meaningful l2 distance metric so we can use nearestNeighbor search directly. 

Add SPECTER paper embedding similarity support

---

aws_bootstrap.sh

This is the only place I have found where we reference Copr (implicitly) in the documentation. We will switch to using Bintray as this is more reliable and has the archive of previous releases.
FYI, @jobergum, @bratseth

Use the bintray repository for RPMs. 

---

basic-search-on-docker-swarm/docker-compose.yml
basic-search-on-docker-swarm/scripts/deploy.sh
basic-search-on-docker-swarm/scripts/feed.sh
basic-search-on-docker-swarm/scripts/generate_hosts_xml.sh

Rework docker-compose for the following enhancements:
- names don't change when containers restart, so hosts.xml stays valid.
- names can be aligned with aliases, so generate_hosts_xml.sh is simpler.
- containers are kept separate so port bindings can be set individually.
- each container can be constrained to a specific node, so in a cluster we have control on their repartition.
generate_hosts_xml.sh is adapted accordingly.
On top of that, the syntax for python code in scripts has been updated for python 3 compatibility.

Swarm example enhancements

---

vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/RelatedArticlesByWeakAndSearcherTest.java

Reverts vespa-engine/sample-apps#512 - as it is deployed, both code and Vespa is on the latest and greatest, so can enable tests again

Revert "make deployable"

---

http-api-using-request-handlers-and-processors/src/main/application/hosts.xml
http-api-using-request-handlers-and-processors/src/main/application/searchdefinitions/music.sd
http-api-using-request-handlers-and-processors/src/main/application/services.xml
http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DataProcessor.java
http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DemoDocumentProcessor.java
http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DemoFreezableComponent.java

This PR is mainly to track an issue that I've seen when attempting to store DocumentOperations from a Processor, once issue addressed this can be merged and serve as reference to the community looking to implement this scenario.

Store Document from Processor

---

vespa-cloud/cord-19-search/src/main/application/services.xml

- content cluster: Won't autoscale now: Less than PT36H52M39.074666666S since last resource change
- container cluster: Cluster is ideally scaled within configured limits
lets try it now, it should just swap the two nodes in each cluster with smaller ones

use less resources

---

transformers/README.md

- ERROR: Command 'pip3 install -qqq torch transformers onnx onnxruntime' returned code 137
- 137 is OOM

remove -qqq for more output

---

model-evaluation/README.md

- {{ and }} are parsed in liquid
- https://github.com/vespa-engine/sample-apps/runs/2734965244?check_suite_focus=true

woarkaround Liquid Exception

---

vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd

- to support search-as-you-type
FYI @olemagnusnorum 
PS: I did not set stemming on the gram fields, I don't think that is needed, could remove in the search-as-you-type sample app, too

Add gram-matching fields

---

vespa-cloud/search-suggestion/src/main/application/services.xml

Based on:
> Failed to prepare application: Invalid application package: Error loading vespa-team.search-suggestion: No allocation possible within limits: from 2 nodes with [vcpu: 2.0, memory: 8.0 Gb, disk 50.0 Gb, bandwidth: 0.3 Gbps, storage type: local] to 3 nodes with [vcpu: 2.0, memory: 8.0 Gb, disk 50.0 Gb, bandwidth: 0.3 Gbps, storage type: local]. Nearest allowed node resources: [vcpu: 2.0, memory: 4.0 Gb, disk 50.0 Gb, bandwidth: 0.3 Gbps, storage type: local]

try local disk

---

vespa-cloud/cord-19-search/src/main/application/services.xml

Got this when deploying:
> Failed to prepare application: Invalid application package: Error loading vespa-team.cord-19: No allocation possible within limits: from 2 nodes with [vcpu: 4.0, memory: 8.0 Gb, disk 50.0 Gb, bandwidth: 0.3 Gbps, storage type: local] to 4 nodes with [vcpu: 4.0, memory: 8.0 Gb, disk 50.0 Gb, bandwidth: 0.3 Gbps, storage type: local]. Nearest allowed node resources: [vcpu: 2.0, memory: 4.0 Gb, disk 50.0 Gb, bandwidth: 0.3 Gbps, storage type: local]
So I think a 100G disk will do.
(But surprised why the deployment fails here, this is from a system test run that anyway is downscaled and uses default resources. But in a way better to fail early :-)

Deploy with a valid resource config

---

album-recommendation-selfhosted/src/test/resources/A-Head-Full-of-Dreams.json
album-recommendation-selfhosted/src/test/resources/Hardwired...To-Self-Destruct.json
album-recommendation-selfhosted/src/test/resources/Liebe-ist-fur-alle-da.json
album-recommendation-selfhosted/src/test/resources/Love-Is-Here-To-Stay.json
album-recommendation-selfhosted/src/test/resources/When-We-All-Fall-Asleep-Where-Do-We-Go.json
basic-search-on-gke/music-data-1.json
basic-search-on-gke/music-data-2.json
vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/DocTypeDocProcTest.java
vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/ProductTypeRefinerDocProcTest.java
vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/ProductTypeTokenizerDocProcTest.java
vespa-cloud/album-recommendation-docproc/src/test/resources/A-Head-Full-of-Dreams-lyrics.json
vespa-cloud/album-recommendation-docproc/src/test/resources/A-Head-Full-of-Dreams-product.json
vespa-cloud/album-recommendation-docproc/src/test/resources/A-Head-Full-of-Dreams.json
vespa-cloud/album-recommendation-docproc/src/test/resources/Hardwired...To-Self-Destruct.json
vespa-cloud/album-recommendation-docproc/src/test/resources/Love-Is-Here-To-Stay.json
vespa-cloud/album-recommendation-searcher/src/test/java/ai/vespa/example/album/FeedAndSearchSystemTest.java
vespa-cloud/album-recommendation-searcher/src/test/java/ai/vespa/example/album/MetalProductionTest.java
vespa-cloud/album-recommendation-searcher/src/test/java/ai/vespa/example/album/MetalSearcherTest.java
vespa-cloud/album-recommendation-searcher/src/test/resources/A-Head-Full-of-Dreams.json
vespa-cloud/album-recommendation-searcher/src/test/resources/Hardwired...To-Self-Destruct.json
vespa-cloud/album-recommendation-searcher/src/test/resources/Love-Is-Here-To-Stay.json
vespa-cloud/album-recommendation/src/test/resources/A-Head-Full-of-Dreams.json
vespa-cloud/album-recommendation/src/test/resources/Hardwired...To-Self-Destruct.json
vespa-cloud/album-recommendation/src/test/resources/Love-Is-Here-To-Stay.json

- Put id's in documents to make cli commands nicer
- Use text ids to avoid any beginner confusion about having to
generate numeric ids

Ids in documents

---

vespa-cloud/cord-19-search/src/main/application/search/query-profiles/default.xml

- Speeds up search by 20x as less candidates are exposed to first phase function and grouping framework. Typical response improvement from 1 second to 50 ms. 
- Added presentation timing information to add to frontend

Add timing and replace OR with weakAnd

---

test/_test_config.yml

Hoping that after increasing memory for the tester container https://github.com/vespa-engine/sample-apps/pull/726 this change will just work. 

Add more apps to sample application testing 

---

screwdriver.yaml

I think this image is renamed from `vespaengine/vespa-pipeline` to `vespaengine/pipeline` on docker hub - on my local machine:
```
$ docker images
REPOSITORY                            TAG       IMAGE ID       CREATED        SIZE
vespaengine/vespa                     latest    808ff5c4b90c   5 days ago     2.05GB
vespaengine/pipeline                  latest    dcabf96a02a6   13 days ago    520MB
docker.ouroath.com:4443/vespa/rhel8   latest    8978780ab388   3 weeks ago    456MB
vespaengine/vespa-build-centos7       latest    f1fff3731f11   4 weeks ago    2.16GB
vespaengine/vespa-pipeline            latest    ddcd35dbc329   4 months ago   508MB
```
per screwdriver.yaml it is pushed as `docker push docker.io/vespaengine/pipeline:latest `- but the readme says `docker pull …

Use updated Docker image

---

screwdriver.yaml

The image is now pushed with correct name

Revert "Use updated Docker image"

---

vespa-chinese-linguistics/README.md

- the path of component and config is wrong
- In my test with version 7.503.19, the Interface `Linguistics` add a function `equals` that isn't overrode in `JiebaLinguistics`.

fix services.xml

---

album-recommendation-java/src/main/application/services.xml
album-recommendation-java/src/main/java/ai/vespa/example/album/MetalSearcher.java
album-recommendation-java/src/main/java/ai/vespa/example/album/SetFilterSearcher.java
album-recommendation-java/src/test/java/ai/vespa/example/album/EquivSearcherTest.java
album-recommendation-java/src/test/java/ai/vespa/example/album/MetalSearcherTest.java
album-recommendation-java/src/test/java/ai/vespa/example/album/SetFilterSearcherTest.java

Added a simple example of how to do set filtering since YQL parsing of large (1000's) keys using weighted set yql query operator is costly. 

Add example of set filtering

---

screwdriver.yaml

Ensure Java binary from JAVA_HOME is first on path

---

test/_test_config.yml

Reverts vespa-engine/sample-apps#808 - docker crashed, I think we run on max settings - I think we should look into shrinking some containers, we start 10 nodes in separate docker containers here

Revert "test multinode-HA"

---

screwdriver.yaml

- the multinode-HA failed at the last step (starting content nodes)
- presumably OOM, lets see if verbose is useful
If it really is memory that is the problem, we are already using the max available resources. It is possible to work around by running only one config server in the auto testing, this will test 90% of the guide. We will see
... or @hmusum

Verbose test run

---

operations/album-recommendation-monitoring/album-recommendation-random-data/Dockerfile

Still get
````
Step 4/7 : RUN mvn -f /home/app/pom.xml --batch-mode -q clean package
---> Running in 93a7a623816a
unexpected EOF
sentinel-873624> exit code: 1
````
remove quiet option for now ... @lesters  it seems pexpect is timing out, default timeout is 30 minutes, https://cd.screwdriver.cd/pipelines/7021/builds/769378/steps/run-tests

More mvn output

---

screwdriver.yaml

>curl: /lib64/libc.so.6: version `GLIBC_2.22' not found (required by /home/linuxbrew/.linuxbrew/lib/libldap.so.2)

Try to unbreak curl

---

examples/http-api-using-request-handlers-and-processors/src/main/application/services.xml
examples/operations/basic-search-on-gke/templates/services.xml
model-evaluation/README.md
model-evaluation/src/main/application/services.xml
msmarco-ranking/document-ranking.md
text-image-search/README.md
text-image-search/src/main/application/services.xml

- Change redundancy to 2
- Disable computing of image embeddings per test run for now, to reduce turnaround time on testing

Redundancy should be 2 MERGEOK

---

screwdriver.yaml

This can allow us to add tests for notebooks that are part of sample apps, especially for pyvespa. It steps through all steps in the notebook, so we know if something broke. I'm uncertain yet how you add actual test for output etc, but this will be a good start :)
```
pytest --nbmake msmarco-ranking/src/main/python/model-exporting.ipynb 
=========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.8.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/bergum/cloud-ultimate/sample-apps/msmarco-ranking/src/main/python
plugins: anyio-2.2.0, nbmake-1.3.0
collected 1 item …
```

Add nbmake and pytest for testing of Notebooks

---

text-search/README.md

For consistency with other sample apps. Cache is also more reliable now, so this
is no longer needed.
@kkraune

Remove -f flag MERGEOK

---

examples/operations/album-recommendation-monitoring/grafana/provisioning/dashboards/vespa-detailed-monitoring.json

- these are documents per content node, not unique docs

Correct graph title

---

examples/generic-request-processing/pom.xml
examples/http-api-using-request-handlers-and-processors/pom.xml
examples/operations/album-recommendation-monitoring/album-recommendation-random-data/pom.xml
examples/predicate-fields/pom.xml

Reverts vespa-engine/sample-apps#984
Cannot build using 17 and deploy into the current vespa7-in-11 containers:
````
[2022-06-09 11:38:43.664] ERROR   : container        Container.com.yahoo.jdisc.core.StandaloneMain	JDisc exiting: Throwable caught: \nexception=\njava.lang.UnsupportedClassVersionError: com/yahoo/example/SubqueriesSearcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 ...
````
fyi @bratseth

Revert "Set release 17 MERGEOK"

---

msmarco-ranking/src/main/python/model-exporting.ipynb
screwdriver.yaml

```
ValueError: Unsupported ONNX opset version: 15
21:58:11 =============================== warnings summary ===============================
21:58:11 ../../../../../usr/local/lib/python3.6/site-packages/_pytest/nodes.py:140
21:58:11   /usr/local/lib/python3.6/site-packages/_pytest/nodes.py:140: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to NotebookFile is deprecated. Please use the (path: pathlib.Path) argument instead.
21:58:11   See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
21:58:11     return super().__call__(*k, **kw)
21:58:11 
21:58:11 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
21:58:11 =========================== short test summary info …
```

Try to fix test infra after upgrading opset version for transformer exports 

---

simple-semantic-search/README.md
test/test.py

- Test script changes:
- Also check for test attributes on &lt;p&gt; - there is always something visible one can attach test commands to
- support a "macro" - predefined steps, like docker start + deploy. Can then use this more places to invoke common / shared steps
note: need the remove container step for the full test script run, where all files are tested in sequence. This is also helpful for the user, it is a common use case to rerun

Add testing to new sample app

---

examples/operations/README.md

Vespaengine is now mult-arch

---

dense-passage-retrieval-with-ann/requirements.txt

Reverts vespa-engine/sample-apps#1114
failed with
```
ERROR: Could not find a version that satisfies the requirement torch==1.13.1 (from versions: 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2)
03:58:16 ERROR: No matching distribution found for torch==1.13.1
```

Revert "Bump torch from 1.7.1 to 1.13.1 in /dense-passage-retrieval-with-ann"

---

text-image-search/src/python/requirements.txt

with 2.0 we get the below - lock version for now
````
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::unflatten' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
````

do not use torch 2.* (yet)

---

billion-scale-image-search/README.md
billion-scale-vector-search/README.md
commerce-product-ranking/README.md
custom-embeddings/README.md
dense-passage-retrieval-with-ann/README.md
examples/part-purchases-demo/README.md
examples/predicate-fields/README.md
incremental-search/search-as-you-type/README.md
incremental-search/search-suggestions/README.md
model-inference/README.md
msmarco-ranking/document-ranking-README.md
text-image-search/README.md
text-search/README.md
transformers/README.md

- Primarily unifying the "deploy to cloud" section with a link
- typos and minor text fixes, too - guides are the same
- a few more files to go, next PR - this one in big enough

Fix cloud deployment instructions

---

dense-passage-retrieval-with-ann/requirements.txt

- Reverts vespa-engine/sample-apps#1217
- build is broken, revert for now - this app will be rewritten

Revert "Bump transformers from 4.10.3 to 4.30.0 in /dense-passage-retrieval-with-ann"

---

examples/operations/multinode-HA/docker-compose.yaml

This change makes the naming of the vespa docker containers and FQDN hostnames correct and consistent with the `services.xml`.

examples/operations/multinode-HA: docker-compose consistent naming

---

vector-streaming-search/README.md

- `vespa auth cert` fails with the current readme, as it writes clients.pem into the app package
- instead, use same flow as in the other sample apps, linking to the common doc
- once we have the new `vespa auth cert` without the .pem write, all sample apps will be rewritten to a better flow and simplified (the below is not optimal but will at least not fail)
.... or @bratseth

Unbreak Cloud deployment MERGEOK

---

examples/embedding-service/README.md
examples/embedding-service/src/main/application/services.xml

The PR adds more memory to the embedding-service node to avoid core dumps (see https://jira.ouryahoo.com/browse/VESPA-26950 and https://jira.ouryahoo.com/browse/VESPA-26973).
In addition, most models are now disabled by default to save memory and instructions for how to enable more models have been added.
Instructions for deploying to cloud have also been added.

Add more RAM for embedding-service node and add info

---

examples/vespa-chinese-linguistics/README.md
examples/vespa-chinese-linguistics/pom.xml
examples/vespa-chinese-linguistics/src/main/java/com/qihoo/language/JiebaLinguistics.java
examples/vespa-chinese-linguistics/src/main/java/com/qihoo/language/JiebaTokenizer.java
examples/vespa-chinese-linguistics/src/test/java/com/qihoo/language/JiebaTokenizerTest.java

- fix user dict load error(previous version dictionary path should be a resource path, not a absolute file path)
- fix index word not in lower case, word with upper case letter will not match
- fix query tokenizer should use SegMode.SEARCH

fix errors in vespa-chinese-linguistics

---

use-case-shopping/src/test/application/tests/system-test/product-search-test.json

- fix https://cd.screwdriver.cd/pipelines/7038/builds/894447/steps/run-tests
```
07:54:36 ********************************************************************************
07:54:36 * vespa test src/test/application/tests/system-test/product-search-test.json
07:54:36 * (Expecting 'Success')
07:54:36 ********************************************************************************
07:54:37 Product Search:
07:54:37 Error: error in Step 1: feed product document: no such service: "default": known services: container
07:54:37 Hint: See https://docs.vespa.ai/en/reference/testing
07:54:37 ERROR: Expected output 'Success' not found in command 'vespa test src/test/application/tests/system-test/product-search-test.json'
```

Set correct container cluster name

---

msmarco-ranking/src/main/python/model-exporting.ipynb

- with 1.16.0 we get https://cd.screwdriver.cd/pipelines/7038/builds/899796/steps/run-tests
- works with 1.15.1
```
from transformers import AutoTokenizer, AutoModelForSequenceClassification
04:06:22 import transformers.convert_graph_to_onnx as onnx_convert
04:06:22 
04:06:22 cross_model = "cross-encoder/ms-marco-MiniLM-L-6-v2"
04:06:22 output_file = "ms-marco-MiniLM-L-6-v2.onnx"
04:06:22 tokenizer = AutoTokenizer.from_pretrained(cross_model)
04:06:22 model = AutoModelForSequenceClassification.from_pretrained(cross_model)
04:06:22 model = model.eval()
04:06:22 pipeline = transformers.pipeline("text-classification", model=model, tokenizer=tokenizer)
04:06:22 onnx_convert.convert_pytorch(pipeline, opset=12, output=Path(output_file), use_external_format=False)
04:06:22 …
```

Lock to 1.15.1 for now

---

examples/lucene-linguistics/README.md

Missing or empty configDir now gives slightly more informative error messages. Trying to use application package root now says that this is an illegal value, I think that is good enough
@dainiusjocas error messages are slightly better, although not quite there yet, but wanted to update with how this is today. Please have a look

Update doc about common issues with configDir missing or being empty

---

billion-scale-image-search/README.md

Error message when not specifying protocol version (=> will use http 2):
07:51:23 curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
07:51:23 sentinel-254488> exit code: 92
07:51:23 
07:51:23 ERROR: Command 'curl -L -o img_emb_0000.npy  https://the-eye.eu/public/AI/cah/laion5b/embeddings/laion2B-en/img_emb/img_emb_0000.npy' returned code 92
07:51:23

Use http 1.1, server has misconfigured http 2 setup

---

examples/operations/multinode/README.md

Metric snapshot might not be updated immediately

Wait for content.proton.documentdb.documents.total.last

---

text-search/bin/download-msmarco.sh

It seems that the old location for the msmarco datasets is invalid. They have been moved as shown below:
```
~/text-search
❯ curl --head https://msmarco.blob.core.windows.net/msmarcoranking/msmarco-doctrain-queries.tsv.gz
HTTP/1.1 404 The specified resource does not exist.
Transfer-Encoding: chunked
Server: Blob Service Version 1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 5cd1bf4f-501e-0067-144d-713590000000
Date: Fri, 08 Mar 2024 11:43:48 GMT
~/text-search
❯ curl --head https://msmarco.z22.web.core.windows.net/msmarcoranking/msmarco-doctrain-queries.tsv.gz …
```

change msmarco dataset location

---

commerce-product-ranking/README.md

Wait longer since it's a constrained environment for testing, and the sample app loads many models.

Wait longer for stateless container to start

---

.github/workflows/build.yml
screwdriver.yaml

- adds a new workflow that tests the building of the sample apps
- removes the job from screwdriver
Part of the process of retiring Screwdriver as CI/CD runner.
Related PRs:
- https://github.com/vespa-engine/documentation/pull/3295
- https://github.com/vespa-engine/documentation/pull/3296
- https://github.com/vespa-engine/documentation/pull/3301

chore: migrate workflow for building sample apps to Github Actions

---

.github/workflows/link-checker.yml
screwdriver.yaml

- Setup a Github Actions workflow to check documentation links.
- Removed the existing job from Screwdriver
Migrate the ["link-checker" Screwdriver](https://github.com/vespa-engine/sample-apps/blob/1ff9e32788ecb8d9bee4f6cb3abb7337343439a0/screwdriver.yaml#L23-L58) job to Github Actions.
More PRs using the same `jekyll-link-checker.yml` workflow:
- https://github.com/vespaai/blog/pull/545
- https://github.com/vespa-engine/documentation/pull/3299
---
> ⚠️ Requires PR to be merged first: https://github.com/vespa-engine/gh-actions/pull/6

feat: add GitHub Actions workflow for link checking on documentation MERGEOK

---

.github/workflows/verify-notebooks.yml

Migrates the "Verify Notebooks" workflow to Github Actions.
Part of the process of retiring Screwdriver as CI/CD runner.
N/A

feat: add workflow to verify notebooks

---

examples/training-artifacts/101/ch2/ecommerce/validation-overrides.xml
examples/training-artifacts/101/ch3/queries.http
examples/training-artifacts/101/ch3/sales-data.csv
examples/training-artifacts/101/ch3/sales-data.jsonl

This is the one with grouping. We'll reuse the [part-purchases-demo](https://github.com/vespa-engine/sample-apps/tree/master/examples/part-purchases-demo) example, just with a little more data.

Vespa 101 chapter 3 lab data

---

.github/workflows/build.yml
.github/workflows/feed.yml
.github/workflows/link-checker.yml
.github/workflows/verify-guides-main.yml

Gemfile.lock is only used when generating the feed to doc search, so we _could_ feed on changes to it. But we will find out soon enough if something breaks on deps, and it is wasteful to generate the feed job for every dep change, that is quite often

ignore deps changes

---

visual-retrieval-colpali/backend/colpali.py

This does the sim map calculation a bit more efficient - does no longer use matplotlib. 
Means we no longer get the image annotations though.

(colpalidemo) calc sim maps more efficient and full scale

---

visual-retrieval-colpali/backend/colpali.py
visual-retrieval-colpali/colpali-with-snippets/schemas/pdf_page.sd
visual-retrieval-colpali/main.py

compute similarity map in vespa

---

retrieval-augmented-generation/README.md

One of the queries is missing two line continuation characters. Tested on macOS with Zsh.

Add missing backslashes to README.md

---

visual-retrieval-colpali/backend/colpali.py

Hopefully the last fix. 
Tokens without the special '_' occur sometimes and were previously filtered. 
Try e.g. `norwegian`

(colpalidemo) improve token filtering

---

visual-retrieval-colpali/src/main.py

By reverting this to a list we ensure that the images are always given to gemini in the order they appear in the result set.
This matters because some times gemini talks about "the first image", "the second image" or "the third image" and now it will always match up.
Also avoid waiting 0.2 seconds when it's not needed.

give images to gemini in correct order

---

visual-retrieval-colpali/src/frontend/app.py

- Match `page_no` also in display (increment by 1) 
- Format search time to 3 significant digits. 
- Refactor from using `NotStr()` to components. 
- Fire new `/search` also on radio button change.

(colpalidemo) page no incr, fire on radio change

---

visual-retrieval-colpali/src/backend/vespa_app.py

We discovered that the globally most similar documents were sometimes not in the top 10 (thus not reranked for second phase) for the `Colpali` radio button (Retrieval binary-> 1st phase `max_sim_binary`-> 2nd phase `max_sim`). 
- Increased `rerankCount` to 100 for `Colpali` rank option
- Added `hnsw.exploreAdditionalHits` to increase accuracy in retrieval. 
This makes this option quite a bit slower, but increases accuracy. 
Thinking that it is good to show tradeoff options. 
Still not sure which one should be default though...?

(colpalidemo) Thomasht86/exploreadditionalhits

---

visual-retrieval-colpali/prepare_feed_deploy.py
visual-retrieval-colpali/src/backend/vespa_app.py
visual-retrieval-colpali/src/frontend/app.py
visual-retrieval-colpali/src/main.py

Unify naming of rank profiles, and adapt "Hybrid BM25+ColPali" to do retrieval with nearestNeighbor or userQuery() and also use bm25 scores in 2nd phase. 
cc: @jobergum

(colpalidemo) Thomasht86/update ranking

---

README.md
examples/operations/README.md

@lperry25 with this, all the sample applications are found from the readme(s) in this repo - so you can change the links in console to https://github.com/vespa-cloud to here instead. A little less confusion.
I will move the applications separately

Add sample application pointers

---

billion-scale-image-search/README.md
billion-scale-vector-search/README.md
commerce-product-ranking/README.md
custom-embeddings/README.md
examples/document-processing/README.md
examples/generic-request-processing/README.md
examples/http-api-using-request-handlers-and-processors/README.md
examples/in-context-learning/README.md
examples/lucene-linguistics/README.md
examples/multiple-bundles/README.md
examples/part-purchases-demo/README.md
examples/predicate-fields/README.md
incremental-search/search-as-you-type/README.md
incremental-search/search-suggestions/README.md
model-inference/README.md
msmarco-ranking/README.md
multi-vector-indexing/README.md
multilingual-search/README.md
retrieval-augmented-generation/README.md
text-image-search/README.md
text-search/README.md
transformers/README.md
use-case-shopping/README.md
vector-streaming-search/README.md

Bind only to 127.0.0.1 in examples

---

commerce-product-ranking/notebooks/Train-xgboost.ipynb

Fix for https://github.com/vespa-engine/vespa/issues/31747
We have a few notebooks that are part of sample apps, they could maybe be candidates for moving to the notebook examples in pyvespa @thomasht86 

Make labels integers for xgboost 2.x

---

.github/workflows/feed.yml

Reverts vespa-engine/sample-apps#1596
feeding not working (will debug after revert): 
```
CompletedProcess(args=['./vespa', 'feed', '-a', 'vespacloud-docsearch.cloud-enclave', '-t', 'https://cloud-enclave.vespacloud-docsearch.vespa-team.aws-us-east-1c.z.vespa-app.cloud/', 'vespaapps_index.json'], returncode=1, stdout=b'', stderr=b'Error: open /home/runner/.vespa/vespacloud-docsearch.api-key.pem: no such file or directory\n')
```

Revert "simplify, not needed"

---

retrieval-augmented-generation/README.md
retrieval-augmented-generation/services.xml

Feel free to rewrite and reformat as you see fit.
FYI: @tokle

Use secret store for rag sample app.

---

examples/README.md

first step cleaning up the example set, by linking the missing examples. Next step is harmonizing it with the top-level readme

add missing examples to readme

---

test/pseudo_terminal.py

- avoid ERROR: 'float' object cannot be interpreted as an integer
CC @thomasht86  this started failing auto testing, could be the python version was bumped / something made this stricter?

use integers

---

examples/lucene-linguistics/add-token-filter-factory/README.md
examples/lucene-linguistics/add-token-filter-factory/pom.xml
examples/lucene-linguistics/add-token-filter-factory/services.xml
examples/lucene-linguistics/add-token-filter-factory/src/main/java/ai/vespa/test/MyFilterFactory.java
examples/lucene-linguistics/add-token-filter-factory/src/main/resources/META-INF/services/org.apache.lucene.analysis.TokenFilterFactory

This was the only way I could make plugging in your own TokenFilter components work;
the SPI mechanism used by lucene pretty much requires that these must be in the same
bundle so that they share classloader and classpath.
@bratseth please review
@gjoranv FYI
@radu-gheorghe FYI
@dainiusjocas do you have any comments / insights?

add working example of building your own lucene-linguistics component

---

test/test.py

* Updates the "init-deploy" macro to use `./app` for vespa deploy commands.
Use the new directory structure defined in https://github.com/vespa-engine/sample-apps/pull/1670
The following apps needs to be updated with the new structure before the tests are fully passing:

fix: update deployment command to include application path

---

examples/operations/monitoring/album-recommendation-monitoring/prometheus/prometheus-cloud.yml
examples/operations/monitoring/vespa-grafana-terraform/modules/alerts/main.tf

And remove unnecessary `org_id`

Use 'Vespa' consumer for prometheus cloud config

---

examples/operations/multinode-HA/README.md

Update based on feedback on Slack, there was some misunderstandings about how and why this is done this way.

Try to make startup sequence note less ambigious

---

examples/operations/multinode/README.md

be more specific about not reducing cfg memory

---

.github/workflows/update-cloud-samples.yml

Updates to the `.github/workflows/update-cloud-samples.yml` workflow:
- fix the env name: `s/S3_BUCKET/AWS_S3_BUCKET_NAME/`
- improve the handling of dry-run, by setting it once.
- fix upload issue 😊 
.
<details>
<summary><em>Bonus:</em> Click here for Copilot PR review</summary>
**Workflow improvements:**
* Added a `DRY_RUN` environment variable to control dry-run behavior based on the event type and branch, with a note to remove it once a separate S3 bucket is used for the 'Vespa Cloud CD' environment.
* Updated S3 upload and copy steps to use the new `DRY_RUN` variable via `AWS_S3_OPTIONS`, ensuring dry-run mode is correctly applied.
* Changed the CloudFront cache invalidation step to use the `DRY_RUN` variable through the `ECHO` environment variable, making the dry-run logic …

fix(deploy): S3 bucket name variable

---

.github/workflows/update-cloud-samples.yml
console-sample-apps.json

(test) Add ragblueprint to console deployment
