README.md, basic-search-java/README.md, basic-search-tensor/README.md, basic-search-tensor/src/main/resources/playground/css/playground.css, basic-search/README.md, blog-recommendation/README.md, blog-search/README.md, blog-tutorial-shared/README.md, boolean-search/README.md, http-api-using-request-handlers-and-processors/README.md, http-api-using-searcher/README.md
=> Add copyright header

basic-search-java/src/main/application/services.xml, basic-search-java/src/main/java/com/mydomain/example/ExampleProcessor.java, basic-search-java/src/main/java/com/mydomain/example/StringData.java, basic-search-java/src/main/resources/configdefinitions/example-processor.def, basic-search-java/src/test/java/com/mydomain/example/ApplicationMain.java, basic-search-java/src/test/java/com/mydomain/example/ApplicationTest.java, basic-search-java/src/test/java/com/mydomain/example/ExampleProcessorTest.java, http-api-using-request-handlers-and-processors/src/main/application/services.xml, http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/AnnotatingProcessor.java, http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DataProcessor.java, http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DemoComponent.java, http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DemoHandler.java, http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DemoRenderer.java, http-api-using-request-handlers-and-processors/src/main/resources/configdefinitions/demo.def, http-api-using-request-handlers-and-processors/src/test/java/com/mydomain/demo/ApplicationMain.java, http-api-using-searcher/src/main/application/services.xml, http-api-using-searcher/src/main/java/com/mydomain/demo/DemoComponent.java, http-api-using-searcher/src/main/java/com/mydomain/demo/DemoHandler.java, http-api-using-searcher/src/main/java/com/mydomain/demo/DemoRenderer.java, http-api-using-searcher/src/main/java/com/mydomain/demo/DemoSearcher.java, http-api-using-searcher/src/main/resources/configdefinitions/demo.def, http-api-using-searcher/src/test/java/com/mydomain/demo/ApplicationMain.java
=> Use 'package' instead of 'namespace' in custom def files.

basic-search-java/pom.xml, basic-search-tensor/pom.xml, boolean-search/pom.xml, http-api-using-request-handlers-and-processors/pom.xml, http-api-using-searcher/pom.xml
@kkraune or @bjorncs 
+ Remove one unnecessay application dependency.
container-dev _is_ the correct dependency.
=> Remove invalid comments.

basic-search-java/pom.xml, basic-search-tensor/pom.xml, blog-recommendation/pom.xml, blog-search/pom.xml, boolean-search/pom.xml, http-api-using-request-handlers-and-processors/pom.xml, http-api-using-searcher/pom.xml
@tokle please merge - this works, tested from a blank laptop
=> set vespa version

http-api-using-searcher/README.md
=> Fix wrong link to doc

http-api-using-request-handlers-and-processors/src/main/application/services.xml
Much match  <artifactId>http-api-using-request-handlers-and-processors</artifactId> from pom.xml.
@gjoranv
=> Use correct bundle name

basic-search-java/README.md, basic-search-tensor/README.md, blog-recommendation/README.md, blog-search/README.md, boolean-search/README.md, http-api-using-request-handlers-and-processors/README.md, http-api-using-searcher/README.md
@jobergum 
Will make sure we always cleanup the docker container regardless of previously failing steps.
=> Add cleanup as after to guarantee cleanup.

basic-search-tensor/README.md, blog-recommendation/README.md, boolean-search/README.md
=> Encode ampersand and enable one more test step.

basic-search-java/pom.xml
Reverts vespa-engine/sample-apps#26
Broke factory
@kkraune
=> Revert "use container - #3479"

basic-search-java/pom.xml, basic-search-tensor/pom.xml, blog-recommendation/pom.xml, boolean-search/pom.xml, http-api-using-request-handlers-and-processors/pom.xml, http-api-using-searcher/pom.xml
+ Configure maven-versions-plugin to allow auto-updating versions
for vespa and junit
+ Update vespa baseline version
+ Output vespa_version value in phase 'validate' for debugging.
FYI: @kkraune
=> Use container + container-test for all sample apps.

blog-recommendation/src/main/java/com/yahoo/example/UserProfileSearcher.java
=> Fix tensor field in hit

blog-recommendation/.gitignore, blog-recommendation/src/main/application/search/query-profiles/default.xml
with this, one can send a query with a tensor without using a searcher, like
http://localhost:8080/search/?yql=select%20*%20from%20sources%20*%20where%20sddocname%20contains%20%22blog_post%22;&restrict=blog_post&ranking=tensor&ranking.features.query(user_item_cf)=%7B%7Buser_item_cf%3A0%7D%3A0.1%2C%7Buser_item_cf%3A1%7D%3A0.1%2C%7Buser_item_cf%3A2%7D%3A0.1%2C%7Buser_item_cf%3A3%7D%3A0.1%2C%7Buser_item_cf%3A4%7D%3A0.1%2C%7Buser_item_cf%3A5%7D%3A0.1%2C%7Buser_item_cf%3A6%7D%3A0.1%2C%7Buser_item_cf%3A7%7D%3A0.1%2C%7Buser_item_cf%3A8%7D%3A0.1%2C%7Buser_item_cf%3A9%7D%3A0.1%7D
@lesters please merge
=> make tensor in query work

blog-recommendation/README.md, blog-recommendation/src/main/java/com/yahoo/example/UserProfileSearcher.java
=> Fix doc test for blog recommendation app

Vagrantfile
=> need Software Collections for devtoolset

blog-tutorial-shared/src/python/vespaModel.py
In method "serialize_to_disk", variables called "output_dir" and "serializer" not found.
=> Wrong scope

generic-request-processing/README.md
@lesters please review
I don't think escaping is necessary here and some people complained it made it hard to copy paste from source. I'll change the other ones if this works.
=> Don't escape ampersand unnecessarily

basic-search-java/README.md, basic-search-tensor/README.md, blog-recommendation/README.md, blog-search/README.md, boolean-search/README.md, http-api-using-request-handlers-and-processors/README.md, http-api-using-searcher/README.md
=> No need to escape ampersand

model-evaluation/pom.xml, model-evaluation/src/main/application/services.xml
The app works after this fix.
FYI: @geirst
=> Ensure unique Bundle-SymbolicName by adding groupId.

boolean-search/README.md
=> Use vespa-http-client in feed examples.

.gitignore, basic-search-tensor/src/main/java/com/yahoo/example/playground/ExpressionEvaluator.java, basic-search-tensor/src/test/java/com/yahoo/example/playground/ExpressionEvaluatorTest.java
=> Expect type in tensor toString

part-purchases-demo/README.md, part-purchases-demo/parts.py, part-purchases-demo/purchase.csv, part-purchases-demo/purchase.json, part-purchases-demo/src/main/application/hosts.xml, part-purchases-demo/src/main/application/searchdefinitions/purchase.sd, part-purchases-demo/src/main/application/services.xml
- this project can be used for learning along the "Grouping Information in Results"
- the data is a verbatim from the table at the beginning of the section
=> adding purchases demo for grouping guide

basic-search-java/pom.xml, basic-search-tensor/pom.xml, blog-recommendation/pom.xml, boolean-search/pom.xml, generic-request-processing/pom.xml, http-api-using-request-handlers-and-processors/pom.xml, http-api-using-searcher/pom.xml, model-evaluation/pom.xml, pom.xml
- opensource-release-trigger will update version next time it's run
=> Set explicit non-snapshot 7 version.

use-case-shopping/src/main/java/ai/vespa/example/shopping/ReviewProcessor.java
=> Release resources in shopping doc proc MERGEOK

blog-recommendation/src/main/java/com/yahoo/example/UserProfileSearcher.java
@bratseth or @kkraune or @lesters PR
=> Follow deprecation advise and avoid usage of QueryTreeUtils.

use-case-shopping/README.md, use-case-shopping/src/main/resources/templates/footer.html.template, use-case-shopping/src/main/resources/templates/header.html.template
=> Fix links to documentation

blog-tutorial-shared/src/main/scala/com/yahoo/example/blog/CollaborativeFiltering.scala
@kkraune Please review.
This is for incoming changes in tutorial part 2, where documentation is not in sync with sample apps.
=> Generate correct dimension names for user_item_cf tensor

blog-tutorial-shared/src/python/parse.py
Note that this increases the parse time significantly and parsing the 5G file takes 19minutes on my laptop.
=> remove control chars

basic-search-java/README.md, basic-search-java/src/main/java/com/mydomain/example/ExampleSearcher.java
=> Improve logic and simplify

basic-search-java/README.md
- the extra hit code was removed
- bonus: YQL example query
=> wait for full coverage

blog-recommendation/src/main/java/com/yahoo/example/UserProfileSearcher.java
This reverts commit c1ee907c1b074ddbb087144ded1947625028c7e7.
@aressem Please review.
=> Revert "Fix profile search as and was private"

basic-search-java/pom.xml
@aressem : where can I find the latest released vespa version?
=> revert - use released version

.travis.yml, travis/compile-and-test.sh, travis/start-docker-container.sh
=> Build sample apps in container to be able to control the environment.

basic-search-java/src/main/java/com/mydomain/example/Rot13DocumentProcessor.java, basic-search-java/src/test/java/com/mydomain/example/MetalSearcherTest.java, basic-search-java/src/test/java/com/mydomain/example/Rot13DocumentProcessorTest.java
make documenting docprocs easier - copied from documentation
not the best case, so I am not updating basic-search-java readme yet
extra: use junit 5
=> add docproc to sample app

basic-search-hosted/README.md, basic-search-hosted/music-data-1.json, basic-search-hosted/music-data-2.json, basic-search-hosted/music-data-feed.json, basic-search-hosted/music-data-update.json, basic-search-hosted/pom.xml, basic-search-hosted/src/main/application/hosts.xml, basic-search-hosted/src/main/application/search/query-profiles/default.xml, basic-search-hosted/src/main/application/search/query-profiles/extended.xml, basic-search-hosted/src/main/application/search/query-profiles/types/extended.xml, basic-search-hosted/src/main/application/search/query-profiles/types/simple.xml, basic-search-hosted/src/main/application/searchdefinitions/author.sd, basic-search-hosted/src/main/application/searchdefinitions/book.sd, basic-search-hosted/src/main/application/searchdefinitions/person.sd, basic-search-hosted/src/main/application/searchdefinitions/reader.sd, basic-search-hosted/src/main/application/services.xml, basic-search-hosted/src/test/java/com/mydomain/example/TestUtilities.java, basic-search-hosted/src/test/java/com/mydomain/example/_01_BasicTest.java, pom.xml
Reverts vespa-engine/sample-apps#89
@aressem please review. 
Depends on an internal PR.
=> Revert "Revert "Jvenstad/hosted sample app""

basic-search-hosted/README.md, basic-search-hosted/pom.xml
=> get started draft

basic-search-hosted/README.md, basic-search-hosted/pom.xml, basic-search-hosted/src/main/application/deployment.xml, basic-search-hosted/src/main/application/services.xml, basic-search-hosted/src/test/java/com/mydomain/example/_01_BasicTest.java
@kkraune or @oyving or @hmusum please review.
=> Make the application deployable through the CD pipeline

basic-search-tensor/src/main/application/searchdefinitions/music.sd
=> Add explicit value type

basic-search-hosted/README.md
=> Local endpoints must be named "localEndpoints" in test config

basic-search-hosted/src/test/java/com/mydomain/example/TestUtilities.java, basic-search-hosted/src/test/java/com/mydomain/example/_01_BasicTest.java
=> Replace some code with library code, and remove http on 443 workaround

text-search/src/R/compare_rr.R, text-search/src/main/application/deployment.xml, text-search/src/main/application/hosts.xml, text-search/src/main/application/searchdefinitions/msmarco.sd, text-search/src/main/application/services.xml, text-search/src/python/evaluate.py, text-search/src/python/requirements.txt, text-search/src/python/resources/sample_vespa_result
=> move initial code to sample-apps

basic-search-hosted/src/main/application/services.xml
=> use client authorization

text-search/src/main/java/ai/vespa/example/text_search/site/view/SearchRenderer.java
@thigm85 Please review.
Fixes a small bug when paging out of range.
=> Avoid NPE when rendering empty search results

text-search/src/main/java/ai/vespa/example/text_search/site/data/SearchResults.java, text-search/src/main/java/ai/vespa/example/text_search/site/view/SearchRenderer.java, text-search/src/main/java/ai/vespa/example/text_search/site/view/SimpleHtmlBuilder.java, text-search/src/main/resources/templates/search.html.template
@thigm85 Please review. 
Simple option to select ranking profile. Will be expanded later.
=> Add ranking profile option to text search

text-search/src/python/extract-msmarco.py
=> fix path, assume root directory

text-search/src/main/application/search/query-profiles/default.xml
=> increase max hits allowed

text-search/src/python/evaluate.py, text-search/src/python/requirements.txt
@thigm85 Please review.
For preparation of document testing as this does not require installation of an extra python module.
=> Don't require extra libraries for python evaluation script

text-search/src/python/evaluate.py
=> Output MRR score in evaluation script

text-search/README.md
=> Update to testable README for text search sample app

aws_bootstrap.sh
=> Start config server or services, not both

text-search/src/python/test-msmarco-full-ranking.py
Script to evaluate based on dev set or to generate results based on test set. 
Example: Evaluate based on dev set (where we have relevance)
```
./src/python/test-msmarco-full-ranking.py bm25 runid1 data/dev_test_data msmarco-docdev-queries.tsv.gz msmarco-docdev-qrels.tsv.gz
```
Example: Predict based on test set (without relevance info)
```
./src/python/test-msmarco-full-ranking.py bm25 runid1 data/dev_test_data msmarco-test2019-queries.tsv.gz
```
=> evaluate dev and generate results based on test

text-embeddings/Dockerfile, text-embeddings/README.md, text-embeddings/bin/convert-to-vespa.py, text-embeddings/bin/download.sh, text-embeddings/bin/evaluation.py, text-embeddings/py-requirements.txt, text-embeddings/src/main/application/hosts.xml, text-embeddings/src/main/application/search/query-profiles/default.xml, text-embeddings/src/main/application/search/query-profiles/types/root.xml, text-embeddings/src/main/application/searchdefinitions/passage.sd, text-embeddings/src/main/application/services.xml
=> Import new text tensor embeddings sample app

text-embeddings/README.md
=> Update with links

text-embeddings/README.md, text-embeddings/bin/evaluation.py, text-embeddings/src/main/application/searchdefinitions/passage.sd
=> Update sample app 

text-embeddings/README.md
=> Update README . formatting .md issues

text-search/src/main/application/searchdefinitions/msmarco.sd, text-search/src/python/collect_training_data.py, text-search/src/python/msmarco.py, text-search/src/python/requirements.txt, text-search/src/python/test-msmarco-full-ranking.py
* Add ranking-profile containing all the interesting features to dump
* create msmarco.py to hold functions that are used accross more than one script
* add script that collect rankfeatures and create a training dataset
=> text search data collection

basic-search-hosted/README.md, basic-search-java/README.md, basic-search-on-docker-swarm/README.md, basic-search-tensor/README.md, blog-recommendation/README.md, blog-search/README.md, boolean-search/README.md, generic-request-processing/README.md, http-api-using-request-handlers-and-processors/README.md, http-api-using-searcher/README.md, model-evaluation/README.md, part-purchases-demo/README.md, text-search/README.md, use-case-shopping/README.md
I have not checked every sample app, assume the auto testing will find any issues
=> export not needed

basic-search-hosted/README.md, basic-search-hosted/pom.xml
=> Update key names

semantic-qa-retrieval/README.md
=> Add output for the full run over all questions

text-search/src/main/application/services.xml, use-case-shopping/src/main/application/services.xml
=> Fix bundle names for shopping and text search README tests

multiple-bundles-lib/pom.xml, multiple-bundles-lib/src/main/java/com/mydomain/lib/FibonacciProducer.java, multiple-bundles-lib/src/main/java/com/mydomain/package-info.java, multiple-bundles/README.md, multiple-bundles/pom.xml, multiple-bundles/src/main/application/hosts.xml, multiple-bundles/src/main/application/services.xml, multiple-bundles/src/main/java/com/mydomain/search/FibonacciSearcher.java, multiple-bundles/src/test/java/com/mydomain/demo/ApplicationMain.java, pom.xml
- Library bundle in separate module/project
FYI: @aressem
=> Add sample app with two bundles.

text-search/src/main/application/searchdefinitions/msmarco.sd, text-search/src/python/collect_training_data.py
Get relevant document if it is contained in the match set, along with random samples from match set.
=> Collect relevant doc plus random samples from match set

travis/compile-and-test.sh
=> Output maven version

multiple-bundles/README.md
copy/paste error from another app
=> Remove stray single quote

multiple-bundles/README.md
=> Check for the actual searcher output

text-search/src/R/linear_models.R, text-search/src/main/application/searchdefinitions/msmarco.sd
=> Exploratory analysis for pointwise linear models

.gitignore, album-recommendation-java/README.md, album-recommendation/README.md
- `data-plane-public-key.pem` ⇨ `clients.pem`
- Added `.gitignore` files for VS Code
=> Fix security/clients.pem paths

text-search/src/main/application/searchdefinitions/msmarco.sd, text-search/src/python/collect_training_data.py
=> Tgm/simplify data collection 

album-recommendation-java/src/test/java/ai/vespa/example/album/FeedAndSearchSystemTest.java
To be able to deploy a whole pipeline we need to be able to run at least one staging test.
=> Make system test a staging test

album-recommendation-java/src/main/application/services.xml, pom.xml
=> Build album-recommendation-java as part of sample-apps build

text-search/src/python/collect_training_data.py
=> simplify parameter list

text-search/README.md
=> include data collection step

text-search/src/python/tfrank.py
=> use right features

text-search/README.md
=> install python dependencies in README

text-search/README.md
=> change data folder

text-search/README.md
=> update data folder

text-search/README.md, text-search/src/python/tfrank.py
=> add run step for tf rank models

text-search/src/python/tfrank.py
=> include python to execute in tfrank script

text-search/README.md, text-search/src/python/tfrank.py
=> Add data_folder as script parameter

README.md, blog-recommendation/README.md, blog-search/README.md, use-case-shopping/README.md
=> first cut top-level README

README.md
=> Spelling + boolean indexing

text-search/README.md
=> update to pip3

album-recommendation-java/README.md, album-recommendation/README.md
- cert generation non-interactive for later test automation
- https git download
=> minor fixes

album-recommendation/README.md
=> no need to click "deployment log"

album-recommendation-java/README.md
=> fix link / key name

album-recommendation-java/README.md
=> better flow

album-recommendation-java/README.md
not quite done yet, but better
=> more details from basic-search-hosted

travis/deploy-album-recommendation-java.sh
=> Specify compatible compile version when compiling

model-evaluation/README.md, model-evaluation/src/main/java/ai/vespa/example/MyHandler.java
=> Fix model evaluation sample app test

text-search/.gitignore, text-search/src/R/compare_rr.R
=> Small updates from the recent past

travis/deploy-album-recommendation-java.sh
=> Set canary upgrade policy during build

text-search/src/main/application/searchdefinitions/msmarco.sd, text-search/src/python/generate-embeddings.py, text-search/src/python/requirements.txt
=> Add first document embedding

text-search/README.md
Can you check if fixes the bug @jonmv?
=> tensorflow 2 requires pip upgrade

album-recommendation-java/src/test/java/ai/vespa/example/album/StagingCommons.java
=> Look for fields in the right place

album-recommendation-java/src/test/java/ai/vespa/example/album/StagingCommons.java
@hmusum please review and merge.
=> Diana, not Diane

album-recommendation-java/src/test/java/ai/vespa/example/album/StagingCommons.java
=> Check correct field

text-search/src/python/generate-embeddings.py
=> avoid normalizing vector with only zeros

album-recommendation-java/src/test/java/ai/vespa/example/album/StagingVerificationTest.java
=> Avoid checking for equality of serialised tensor data

text-search/README.md
=> pip3 progress bar overflows Travis logs

text-search/README.md
=> pip too old to turn off progress bars

text-search/src/python/embedding.py
=> fix field name

multiple-bundles-lib/README.md, multiple-bundles-lib/pom.xml, multiple-bundles/README.md, multiple-bundles/pom.xml
will link to this from documentation
=> added readme, details

album-recommendation-java/src/test/java/ai/vespa/example/album/FeedAndSearchSystemTest.java, basic-search-hosted/README.md, basic-search-hosted/music-data-1.json, basic-search-hosted/music-data-2.json, basic-search-hosted/music-data-feed.json, basic-search-hosted/music-data-update.json, basic-search-hosted/pom.xml, basic-search-hosted/src/main/application/deployment.xml, basic-search-hosted/src/main/application/search/query-profiles/default.xml, basic-search-hosted/src/main/application/search/query-profiles/extended.xml, basic-search-hosted/src/main/application/search/query-profiles/types/extended.xml, basic-search-hosted/src/main/application/search/query-profiles/types/simple.xml, basic-search-hosted/src/main/application/searchdefinitions/author.sd, basic-search-hosted/src/main/application/searchdefinitions/book.sd, basic-search-hosted/src/main/application/searchdefinitions/person.sd, basic-search-hosted/src/main/application/searchdefinitions/reader.sd, basic-search-hosted/src/main/application/services.xml, basic-search-hosted/src/test/java/com/mydomain/example/TestUtilities.java, basic-search-hosted/src/test/java/com/mydomain/example/_01_BasicTest.java
Reverts vespa-engine/sample-apps#185
Broke the build
=> Revert "Kkraune/remove redundant app"

text-search/src/main/application/searchdefinitions/msmarco.sd
Simplify rank profiles to include only what is relevant for the package
=> only compare relevant first phase

text-search/src/main/application/searchdefinitions/msmarco.sd
=> add model trained with or data

text-search/src/python/exploration_app.py
=> update app for package closing

album-recommendation-java/README.md, album-recommendation-java/pom.xml
=> Remove key properties from pom.xml

album-recommendation-java/README.md
=> Fix some links, and remove unnecessary arguments in sample command

album-recommendation-java/README.md
@kkraune please review. Requires https://github.com/vespa-engine/vespa/pull/12268
=> Use new vespa.compile.version alias

album-recommendation-java/README.md
=> always clean and package

pom.xml
Module removed in https://github.com/vespa-engine/sample-apps/pull/238
=> Remove module from pom.xml

vespa-cloud/album-recommendation-prod/src/test/java/ai/vespa/example/SampleStagingSetupTest.java, vespa-cloud/album-recommendation-prod/src/test/java/ai/vespa/example/SampleStagingTest.java, vespa-cloud/album-recommendation-prod/src/test/java/ai/vespa/example/SampleSystemTest.java
=> Fix sample tests - use correct endpoint name

.github/workflows/deploy-vespa-documentation-search.yaml
- this is supposed to work afaik, and is cleaner
=> sey key on top level

vespa-cloud/vespa-documentation-search/src/main/application/deployment.xml, vespa-cloud/vespa-documentation-search/src/main/application/validation-overrides.xml
Reverts vespa-engine/sample-apps#257
=> Revert "Remove deployments in prod"

vespa-cloud/album-recommendation-java/src/main/application/services.xml
=> Add combined cluster to test in staging

vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/MetalSearcherTest.java
=> Disable test which cannot handle two clusters

vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/MetalSearcherTest.java
Reverts vespa-engine/sample-apps#262
@mpolden
=> Revert "Disable test which cannot handle two clusters"

vespa-cloud/album-recommendation-java/src/main/application/services.xml
Reverts vespa-engine/sample-apps#260
@mpolden
=> Revert "Add combined cluster to test in staging"

vespa-cloud/album-recommendation-prod/src/test/java/ai/vespa/example/SampleStagingTest.java, vespa-cloud/album-recommendation/src/main/application/services.xml
=> Fix minor issues to make app work

vespa-cloud/vespa-documentation-search/README.md
=> single quotes everywhere

vespa-cloud/vespa-documentation-search/README.md
=> add Cloud badge

vespa-cloud/album-recommendation-java/README.md, vespa-cloud/album-recommendation-java/src/main/application/search/query-profiles/default.xml, vespa-cloud/album-recommendation-java/src/main/application/search/query-profiles/types/root.xml
please merge - the guide is broken, this fixes it (hopefully) - did not try the test section yet
=> unbreak: configure tensor, fix guide

.github/workflows/deploy-vespa-documentation-search.yaml
Reverts vespa-engine/sample-apps#271 - did not work - will read docs first and see if there is another way
=> Revert "cleanup"

vespa-cloud/album-recommendation-java/README.md
code the secret before storing it - now must decode
=> decode secret MERGEOK

vespa-cloud/album-recommendation-java/README.md
sorry for all the PRs - must make the travis build work ...
=> do the install

vespa-cloud/album-recommendation-java/README.md
now this part of the test also works and does something useful
=> certs also found in centos docker image + asserts MERGEOK

vespa-cloud/vespa-documentation-search/src/main/application/deployment.xml
Reverts vespa-engine/sample-apps#283
=> Revert "Add instance in Japan"

vespa-cloud/vespa-documentation-search/src/main/application/deployment.xml
=> Update deployments, not endpoints

vespa-cloud/cord-19-search/scripts/convert-to-vespa.py
=> Track citatinos within data set

vespa-cloud/cord-19-search/.gitignore, vespa-cloud/cord-19-search/README.md, vespa-cloud/cord-19-search/deployment.xml, vespa-cloud/cord-19-search/pom.xml, vespa-cloud/cord-19-search/scripts/add-citation-data.py, vespa-cloud/cord-19-search/scripts/add-embeddings.py, vespa-cloud/cord-19-search/scripts/convert-to-feed.py, vespa-cloud/cord-19-search/scripts/convert-to-json.py, vespa-cloud/cord-19-search/scripts/convert-to-vespa.py, vespa-cloud/cord-19-search/scripts/python_requirements.txt, vespa-cloud/cord-19-search/src/main/application/deployment.xml, vespa-cloud/cord-19-search/src/main/application/search/query-profiles/default.xml, vespa-cloud/cord-19-search/src/main/application/search/query-profiles/types/root.xml, vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd, vespa-cloud/cord-19-search/src/main/application/services.xml, vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/ApplicationMain.java, vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/FeedAndSearchSystemTest.java, vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/StagingSetupTest.java, vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/StagingVerificationTest.java
=> Move to master branch 

vespa-cloud/cord-19-search/scripts/add-embeddings.py
=> shebang / license

.github/workflows/deploy-vespa-cord-19-search.yaml, vespa-cloud/cord-19-search/README.md
=> typo, add deploy-badge to readme

vespa-cloud/cord-19-search/src/main/application/services.xml
=> Remove rate limiter

vespa-cloud/cord-19-search/blacklist.txt, vespa-cloud/cord-19-search/scripts/wash.py
@jobergum please review and merge.
=> Handle duplicate titles in citation script, and add wash script

vespa-cloud/cord-19-search/blacklist.txt, vespa-cloud/cord-19-search/scripts/add-citation-data.py, vespa-cloud/cord-19-search/scripts/compute-inbound-citations.py
Reverts vespa-engine/sample-apps#301
=> Revert "More small fixes"

vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd
=> Add fields to short summary

vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd, vespa-cloud/cord-19-search/src/main/application/services.xml, vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedPaperSearcher.java, vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedPaperSearcherANN.java
- Add new ranking profiles
- Add related searcher - invoked by /search/?searchChain=related&id=<id> 
=> Add related article search 

vespa-cloud/cord-19-search/README.md
=> Link to cord-19 repo

vespa-cloud/cord-19-search/README.md, vespa-cloud/cord-19-search/experiment-yourself.md
FYI @jobergum  for completing the guide with feeding
=> move file to this repo

vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd
=> Add freshness ranking function

vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedPaperSearcherANN.java
=> Remove the article requested related for from the results by default

vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd
=> Add body_text to short summary

vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedPaperSearcherANN.java
=> use abstract by default

vespa-cloud/cord-19-search/scripts/convert-to-json.py, vespa-cloud/cord-19-search/src/main/application/searchdefinitions/doc.sd
=> Update convert routine to deal with 2020-04-03 version and add fields for t5 summarization

vespa-cloud/cord-19-search/src/main/application/schemas/doc.sd
deployed well on my mac, should be a no-op to the app afaik
@jobergum FYI
=> schema, not searchdef

vespa-cloud/album-recommendation-java/src/main/application/schemas/music.sd, vespa-cloud/album-recommendation/src/main/application/schemas/music.sd, vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd
let the vespa cloud sampleapps use _schema_. will do the others in next pr
=> use schema

vespa-cloud/cord-19-search/src/main/application/schemas/doc.sd
=> Add new fieldsets and rank profiles

vespa-cloud/cord-19-search/src/main/application/search/query-profiles/default.xml
=> Allow more hits

album-recommendation-selfhosted/src/test/resources/Liebe-ist-fur-alle-da.json, album-recommendation-selfhosted/src/test/resources/When-We-All-Fall-Asleep-Where-Do-We-Go.json
these are referred from new documentation
=> two more files for text matching guide

vespa-cloud/cord-19-search/src/main/application/schemas/doc.sd
=> Clean up rank profiles 

vespa-cloud/cord-19-search/src/main/application/services.xml
=> More threads per search

vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd
@kkraune please review and merge
=> always set language to english

vespa-cloud/album-recommendation-docproc/src/main/java/ai/vespa/example/album/LyricsDocumentProcessor.java
=> Map responses, not processings

use-case-shopping/README.md
with this, all files in repo are < 10Mb, so we can experiment with making it a template repo
FYI @lesters
=> compress source data files

album-recommendation-random-data/pom.xml, album-recommendation-random-data/src/main/java/application/VespaQueryFeeder.java
=> Removing Apache commons from pom

vespa-cloud/cord-19-search/scripts/wash.py
=> better names

album-recommendation-monitoring/docker-compose.yml, album-recommendation-monitoring/vespa/VespaAlternateDockerfile
=> Fixed pathing and changed network name

vespa-cloud/album-recommendation-java/README.md
=> track doc link change

vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/RelatedArticlesByNNSearcherTest.java
Follow change in vespa-engine/vespa#13641
=> targetNumHits -> targetHits

vespa-cloud/album-recommendation-docproc/README.md, vespa-cloud/album-recommendation/README.md, vespa-cloud/cord-19-search/README.md
=> fix broken links

album-recommendation-monitoring/grafana/provisioning/dashboards/vespa-detailed-monitoring.json
This is a new and better dashboard imo. Please test that it works with the getting started guide. It can be used to replace that if desired.
=> committed improved dashboard for standard vespa

vespa-cloud/album-recommendation-docproc/README.md, vespa-cloud/album-recommendation-docproc/src/main/application/services.xml
=> correct name

vespa-cloud/album-recommendation-docproc/pom.xml, vespa-cloud/album-recommendation-prod/pom.xml, vespa-cloud/album-recommendation-searcher/pom.xml, vespa-cloud/cord-19-search/pom.xml, vespa-cloud/vespa-documentation-search/pom.xml
=> Use new testrunner

vespa-cloud/album-recommendation-docproc/pom.xml, vespa-cloud/album-recommendation-prod/pom.xml, vespa-cloud/album-recommendation-searcher/pom.xml, vespa-cloud/cord-19-search/pom.xml, vespa-cloud/vespa-documentation-search/pom.xml
Reverts vespa-engine/sample-apps#385
=> Revert "Use new testrunner"

text-search/README.md
=> add force reinstall

semantic-qa-retrieval/bin/evaluation.py, semantic-qa-retrieval/src/main/application/schemas/sentence.sd
=> Improvements 

vespa-cloud/album-recommendation-docproc/src/main/application/schemas/music.sd, vespa-cloud/album-recommendation-docproc/src/main/java/ai/vespa/example/album/ProductTypeRefinerDocProc.java, vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/ProductTypeRefinerDocProcTest.java
I could not find a sample with the simplest of document processors and a unit test - with this, I can make https://docs.vespa.ai/documentation/document-processing.html better
=> add simple docproc and unit test

vespa-cloud/cord-19-search/src/main/application/schemas/doc.sd
=> Add HNSW indexes to embedding fields

vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedArticlesByNNSearcher.java, vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/RelatedArticlesByNNSearcherTest.java
Index refreshed with HNSW enabled. 
=> Starting using ANN instead of NN

vespa-cloud/album-recommendation-searcher/src/test/java/ai/vespa/example/album/StagingCommons.java
We have seen that queries sometimes fail (504 or timeout). Try to run more warmup queries.
=> Run more warmup queries

text-search/README.md
=> Add quiet pip install for text search

vespa-cloud/album-recommendation-docproc/src/main/application/schemas/music.sd, vespa-cloud/album-recommendation-docproc/src/main/java/ai/vespa/example/album/ProductTypeTokenizerDocProc.java, vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/ProductTypeTokenizerDocProcTest.java, vespa-cloud/album-recommendation-docproc/src/test/resources/A-Head-Full-of-Dreams-product.json
=> new test case for input tokenization

vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/ProductTypeTokenizerDocProcTest.java
It feels a little dirty but I could not find a better way to avoid unchecked cast
=> make compile

blog-search/README.md
=> privileged not needed

blog-recommendation/README.md
=> less privileged

vespa-cloud/album-recommendation-searcher/src/main/application/deployment.xml, vespa-cloud/album-recommendation-searcher/src/test/java/ai/vespa/example/album/MetalProductionTest.java
This is all that is needed to run a prod test, right?
=> add a dummy prod test for show

travis/deploy-album-recommendation-searcher.sh
=> simplify for new test runner

vespa-cloud/album-recommendation-searcher/src/main/application/deployment.xml, vespa-cloud/album-recommendation-searcher/src/test/java/ai/vespa/example/album/MetalProductionTest.java
Reverts vespa-engine/sample-apps#409
=> Revert "Revert "add a dummy prod test for show" MERGEOK"

blog-recommendation/src/main/application/schemas/blog_post.sd, blog-recommendation/src/main/application/search/query-profiles/types/root.xml
@kkraune or @aressem Please review and merge.
Should fix documentation tests.
=> Fix recommendation test after converting tensorflow to onnx

vespa-cloud/vespa-documentation-search/src/test/java/ai/vespa/cloud/docsearch/VespaDocProductionTest.java
more fun with a test that does _something_
=> simplistic "metric" test

vespa-cloud/album-recommendation-docproc/src/main/java/ai/vespa/example/album/LyricsDocumentProcessor.java
DocumentAccess.createDefault is deprecated
@jonmv or @aressem please merge - I tested the sample app after this fix
=> use MessageBusDocumentAccess

vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd, vespa-cloud/vespa-documentation-search/src/main/application/services.xml, vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/docsearch/OutLinksDocumentProcessor.java, vespa-cloud/vespa-documentation-search/src/test/java/ai/vespa/cloud/docsearch/VespaDocLinksTest.java
add a simple document processor - so easier to write a meaningful system test in next step.
=> add a link processing doc proc

vespa-cloud/vespa-documentation-search/pom.xml, vespa-cloud/vespa-documentation-search/src/test/java/ai/vespa/cloud/docsearch/VespaDocSystemTest.java
- add a simple search example for completeness
=> simplistic search test

dense-passage-retrieval-with-ann/README.md
=> Fix result section - spell mistake and duplicate

dense-passage-retrieval-with-ann/bin/make-vespa-feed.py
=> Add question encoder document to full feed

vespa-cloud/vespa-documentation-search/README.md
we really need a developer guide in vespa cloud docs, will get to it
=> Add System Test section

vespa-cloud/vespa-documentation-search/src/test/java/ai/vespa/cloud/docsearch/VespaDocSystemTest.java
=> refactor, add comments

vespa-cloud/README.md
- client-authorize removed long time ago
=> add hosts.xml

vespa-cloud/README.md
=> deploy the built app package

vespa-cloud/album-recommendation-docproc/src/main/java/ai/vespa/example/album/LyricsDocumentProcessor.java, vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/docsearch/OutLinksDocumentProcessor.java
=> inject and simplify

vespa-cloud/album-recommendation-docproc/src/main/java/ai/vespa/example/album/DocTypeDocumentProcessor.java, vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/DocTypeDocProcTest.java, vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/ProductTypeRefinerDocProcTest.java, vespa-cloud/album-recommendation-docproc/src/test/java/ai/vespa/example/album/ProductTypeTokenizerDocProcTest.java
will add some more to https://docs.vespa.ai/documentation/documents.html and https://docs.vespa.ai/documentation/document-processing.html to make it easier to get started.
=> add more sample code

dense-passage-retrieval-with-ann/src/main/application/schemas/wiki.sd
=> Explicitly sum output of onnxModel output

pom.xml, vespa-chinese-linguistics/README.md, vespa-chinese-linguistics/pom.xml, vespa-chinese-linguistics/src/main/java/com/qihoo/language/JiebaLinguistics.java, vespa-chinese-linguistics/src/main/java/com/qihoo/language/JiebaTokenizer.java, vespa-chinese-linguistics/src/main/resources/configdefinitions/dicts-loc.def
=> Chinese linguistics

vespa-cloud/vespa-documentation-search/src/main/application/services.xml
=> test with redundancy=1

vespa-cloud/vespa-documentation-search/src/main/application/services.xml
Reverts vespa-engine/sample-apps#453 @bratseth @jobergum
=> Revert "test with redundancy=1"

msmarco-ranking/README.md
This is a placeholder for content to come, but need the url to resolve for submission purpose. 
=> Add placeholder sample app for ms marco submission

vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/RelatedArticlesByNNSearcherTest.java
@jobergum please review and merge.
=> Update unit tests expectations with new feature

.github/workflows/deploy-vespa-documentation-search.yaml
=> Pass source url

pom.xml
=> Add missing apps which uses Java so they get version updated

CONTRIBUTING.md
same as https://github.com/vespa-engine/documentation/pull/1185 @bratseth
=> fix links and linebreaks

README.md
=> fix link, too

.github/workflows/feed.yml, .gitignore, _config.yml, _plugins/vespa_index_generator.rb, feed_to_vespa.py
=> feed sampleapp readme files to doc search

_plugins/vespa_index_generator.rb
=> link to sampleapp dir, not file

_plugins/vespa_index_generator.rb
=> make link to index page work

vespa-cloud/README.md
=> fix broken link

pom.xml, vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd, vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/docsearch/OutLinksDocumentProcessor.java
=> Add more fields for ranking intro

aws_bootstrap.sh
Reverts vespa-engine/sample-apps#427
Switching back. Bintray is shutting down.
=> Revert "Use the bintray repository for RPMs. "

vespa-cloud/album-recommendation/src/main/application/services.xml
=> autoscale memory and disk

vespa-cloud/vespa-documentation-search/README.md, vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd
work in progress, but commit now for easier progress
=> add more rank profiles and guide text

vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd, vespa-cloud/vespa-documentation-search/src/main/application/search/query-profiles/links.xml, vespa-cloud/vespa-documentation-search/src/main/application/search/query-profiles/types/links.xml
=> add rank profiles for tensor ranking + query profile type

album-recommendation-selfhosted/src/main/application/services.xml, blog-recommendation/src/main/application/services.xml, blog-search/src/main/application/services.xml, boolean-search/src/main/application/services.xml, dense-passage-retrieval-with-ann/src/main/application/services.xml, msmarco-ranking/src/main/application/services.xml, news/app-1-getting-started/services.xml, news/app-2-feed-and-query/services.xml, news/app-3-searching/services.xml, news/app-5-recommendation/services.xml, news/app-6-recommendation-with-searchers/src/main/application/services.xml, news/app-7-parent-child/src/main/application/services.xml, part-purchases-demo/src/main/application/services.xml, semantic-qa-retrieval/src/main/application/services.xml, text-search/src/main/application/services.xml, transformers/src/main/application/services.xml, use-case-shopping/src/main/application/services.xml, vespa-cloud/album-recommendation-docproc/src/main/application/services.xml, vespa-cloud/album-recommendation-searcher/src/main/application/services.xml, vespa-cloud/album-recommendation/src/main/application/services.xml
When we set redundancy 1 in examples all users also end up burning themselves by redundancy 1.
@jobergum fyi
=> Redundancy should be 2 by default

vespa-cloud/album-recommendation/src/main/application/services.xml
- no need to autoscale the container for the trial users
- but the content node can grow large with large feeds!
=> higher upper limit

vespa-cloud/album-recommendation-searcher/src/test/java/ai/vespa/example/album/FeedAndSearchSystemTest.java
=> add dummy test to test TestReporter

vespa-cloud/vespa-documentation-search/src/test/java/ai/vespa/cloud/docsearch/VespaDocSystemTest.java
=> add dummy test

.gitignore, screwdriver.yaml
=> add link checker

vespa-cloud/vespa-documentation-search/src/main/application/services.xml
=> try secret store

tensor-playground/README.md
=> link to examples

vespa-cloud/cord-19-search/src/main/application/schemas/doc.sd
=> Correct missing index for hnsw fields

vespa-cloud/cord-19-search/src/main/application/services.xml
Current container and content node suggestions:
- Suggested resources	3	1	2.0	16.0 GB	75.0 GB
- Suggested resources	6	1	0.5	4.0 GB	8.4 GB
I will gradually reduce, taking console screenshots as we go to document the changes :-)
FYI @jobergum
=> use less resources

vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/RelatedArticlesByWeakAndSearcherTest.java
re https://github.com/vespa-engine/vespa/pull/17427 from @bratseth
=> debug output has changed

text-search/src/main/application/services.xml
=> Never expose reply-after

vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/RelatedArticlesByWeakAndSearcherTest.java
work around for now, so it will upgrade and everything will be on latest ...
=> make deployable

http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DemoFreezableComponent.java, screwdriver.yaml
=> build and test sample apps

screwdriver.yaml
=> build only, not deploy

blog-recommendation/README.md
=> deploy using api

blog-recommendation/README.md
=> correct url

blog-recommendation/README.md
=> dump log for debug, no need for mount

blog-recommendation/README.md
Reverts vespa-engine/sample-apps#522
=> Revert "hope _this_ will dump the log"

boolean-search/README.md
=> correct filename

dense-passage-retrieval-with-ann/pom.xml, dense-passage-retrieval-with-ann/src/test/java/ai/vespa/QuestionAnsweringTest.java, dense-passage-retrieval-with-ann/src/test/java/ai/vespa/processor/QADocumentProcessorTest.java, dense-passage-retrieval-with-ann/src/test/java/ai/vespa/searcher/QASearcherTest.java, dense-passage-retrieval-with-ann/src/test/java/ai/vespa/tokenizer/BertTokenizerTest.java
- move to src/test/java
- expect tensor&lt;float&gt;
- junit5
=> make tests runnable with junit5

vespa-cloud/album-recommendation/src/main/application/services.xml
=> only suggest container node autoscale in samples

vespa-cloud/album-recommendation-docproc/README.md, vespa-cloud/album-recommendation-docproc/pom.xml
=> make readme testable

vespa-cloud/album-recommendation-docproc/README.md
minor cleanup, very few functional changes
=> reformat, clean up

boolean-search/pom.xml, boolean-search/src/test/java/com/yahoo/example/SubqueriesSearcherTest.java, dense-passage-retrieval-with-ann/pom.xml, generic-request-processing/pom.xml, generic-request-processing/src/test/java/com/mydomain/example/ApplicationMain.java, generic-request-processing/src/test/java/com/mydomain/example/ApplicationTest.java, generic-request-processing/src/test/java/com/mydomain/example/ExampleProcessorTest.java, http-api-using-request-handlers-and-processors/pom.xml, http-api-using-request-handlers-and-processors/src/test/java/com/mydomain/demo/ApplicationMain.java, msmarco-ranking/pom.xml, msmarco-ranking/src/test/java/ai/vespa/searcher/RetrievalSearcherTest.java, msmarco-ranking/src/test/java/ai/vespa/searcher/colbert/ColbertSearcherTest.java, multiple-bundles-lib/pom.xml, multiple-bundles/pom.xml, multiple-bundles/src/test/java/com/mydomain/demo/ApplicationMain.java, news/app-6-recommendation-with-searchers/pom.xml, news/app-7-parent-child/pom.xml, pom.xml, tensor-playground/pom.xml, tensor-playground/src/test/java/ai/vespa/example/playground/ExpressionEvaluatorTest.java, text-search/pom.xml, text-search/src/test/java/ai/vespa/example/text_search/site/SimpleHtmlBuilderTest.java, text-search/src/test/java/ai/vespa/example/text_search/site/SimpleTemplateTest.java, transformers/pom.xml, use-case-shopping/pom.xml
I make it easier to port to Vespa Cloud, as it requires junit 5. Harmonize - ideally, this is set in a parent, less work next time 
FYI @lesters @jobergum
=> use junit5, fix tests, make them run

vespa-cloud/album-recommendation-docproc/README.md
=> non-functional, readability

dense-passage-retrieval-with-ann/README.md
- less dependent of the docker image == easier to deploy to Vespa Cloud later
- use curl as wget is not default installed on Macs
FYI @jobergum
=> make readme like the others

vespa-cloud/album-recommendation-docproc/README.md
=> correct endpoint

msmarco-ranking/colbert-performance-scaling.md, msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md
=> harmonize with other guides, fix for testing

.gitignore, screwdriver.yaml, test/README.md, test/_test_config.yml, test/pseudo_terminal.py, test/requirements.txt, test/test.py
=> add readme auto testing

vespa-cloud/vespa-documentation-search/README.md
=> Updated vespa_index_generator.rb link

screwdriver.yaml
=> yaml syntax

msmarco-ranking/passage-ranking.md
Hold off merging until post 3 is out
=> Add links to 3 blog posts

screwdriver.yaml
=> ignore dir for link check

incremental-search/search-as-you-type/.gitignore, incremental-search/search-as-you-type/_config.yml, incremental-search/search-as-you-type/feed_to_vespa.py, incremental-search/search-as-you-type/pom.xml, incremental-search/search-as-you-type/src/main/application/schemas/doc.sd, incremental-search/search-as-you-type/src/main/application/services.xml, incremental-search/search-as-you-type/src/main/application/validation-overrides.xml, incremental-search/search-as-you-type/src/main/java/ai/vespa/example/typesearch/SiteHandler.java, incremental-search/search-as-you-type/src/main/resources/configdefinitions/site-handler.def, incremental-search/search-as-you-type/src/main/resources/site/css/main.css, incremental-search/search-as-you-type/src/main/resources/site/index.html, incremental-search/search-as-you-type/src/main/resources/site/js/main.js
=> added search as you type sample app

incremental-search/search-as-you-type/README.md, incremental-search/search-as-you-type/feed_to_vespa.py, incremental-search/search-as-you-type/pom.xml, incremental-search/search-as-you-type/src/main/application/hosts.xml, incremental-search/search-as-you-type/src/main/application/schemas/doc.sd, incremental-search/search-as-you-type/src/main/application/services.xml, incremental-search/search-as-you-type/src/main/resources/site/css/main.css, incremental-search/search-as-you-type/src/main/resources/site/index.html
=> Clean up and started writing readme

vespa-cloud/vespa-documentation-search/src/main/application/services.xml
- ref https://github.com/vespa-engine/vespa/issues/13193#issuecomment-859555543
FYI @olemagnusnorum
=> run indexing chain only once

incremental-search/search-suggestions/.gitignore, incremental-search/search-suggestions/README.md, incremental-search/search-suggestions/_config.yml, incremental-search/search-suggestions/feed_to_vespa.py, incremental-search/search-suggestions/pom.xml, incremental-search/search-suggestions/src/main/application/deployment.xml, incremental-search/search-suggestions/src/main/application/schemas/doc.sd, incremental-search/search-suggestions/src/main/application/schemas/query.sd, incremental-search/search-suggestions/src/main/application/services.xml, incremental-search/search-suggestions/src/main/application/validation-overrides.xml, incremental-search/search-suggestions/src/main/java/ai/vespa/example/searchsuggest/QueryDocumentProcessor.java, incremental-search/search-suggestions/src/main/java/ai/vespa/example/searchsuggest/SiteHandler.java, incremental-search/search-suggestions/src/main/resources/configdefinitions/blocklist.def, incremental-search/search-suggestions/src/main/resources/configdefinitions/site-handler.def, incremental-search/search-suggestions/src/main/resources/site/css/main.css, incremental-search/search-suggestions/src/main/resources/site/index.html, incremental-search/search-suggestions/src/main/resources/site/js/main.js
=> adding the search-suggest sample-app

vespa-cloud/vespa-documentation-search/README.md
=> run plugin

pom.xml
@chunnoo or @olemagnusnorum please merge
=> add to build

incremental-search/search-as-you-type/README.md, test/_test_config.yml
=> wrap lines, add auto testing, bundle install

screwdriver.yaml
CC @aressem  will clean up in images later, I think this will work for now
@chunnoo or @olemagnusnorum  please merge
=> add ruby, bundle is needed MERGEOK

screwdriver.yaml
- so gem can build native extensions
=> add more package MERGEOK

incremental-search/search-as-you-type/src/main/resources/site/css/main.css, incremental-search/search-as-you-type/src/main/resources/site/index.html
=> Sited styled similar to documentation

incremental-search/search-suggestions/src/main/resources/site/css/main.css, incremental-search/search-suggestions/src/main/resources/site/index.html, incremental-search/search-suggestions/src/main/resources/site/js/main.js
=> Documentation like styling on search-suggestion

incremental-search/search-as-you-type/README.md
@chunnoo or @olemagnusnorum please merge
=> wait for container / deploy to start

incremental-search/search-as-you-type/README.md
=> Auto-test that the site is up

test/_test_config.yml
=> auto-test search-suggestions

incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md
=> checks for status in readme and correct site address

test/_test_config.yml
=> test all README files again

incremental-search/search-as-you-type/src/main/resources/site/js/main.js
=> replace sep-tags with ellipsis

vespa-cloud/vespa-documentation-search/src/main/application/schemas/doc.sd
=> example multiline ranking expression

.github/workflows/deploy-search-suggestions.yaml, incremental-search/search-suggestions/src/test/java/ai/vespa/example/searchsuggest/SearchSuggestStagingTest.java, incremental-search/search-suggestions/src/test/java/ai/vespa/example/searchsuggest/SearchSuggestSystemTest.java
=> Add search-suggestion deployment and tests MERGEOK

.github/workflows/deploy-search-suggestions.yaml
=> Update secret MERGEOK

msmarco-ranking/passage-ranking.md
=> Add link to part 4 blog post MERGEOK

incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md
=> no need for docker 6G MERGEOK

README.md, news/README.md, semantic-qa-retrieval/README.md, text-search/README.md, transformers/README.md
=> Update Readme for sample apps 

operations/multinode/README.md
=> Fix minor typos, add clarifications

operations/multinode/README.md
=> run command + use ( \ ) for multi-line

vespa-cloud/search-suggestion/acceptedWords.py, vespa-cloud/search-suggestion/src/main/java/ai/vespa/example/searchsuggest/QueryDocumentProcessor.java
=> Add accepted words check

vespa-cloud/album-recommendation/src/main/application/services.xml, vespa-cloud/cord-19-search/src/main/application/services.xml, vespa-cloud/search-suggestion/src/main/application/services.xml
=> use local storage-type for content cluster resources

vespa-cloud/vespa-documentation-search/access-log-lambda/.gitignore, vespa-cloud/vespa-documentation-search/access-log-lambda/README.md, vespa-cloud/vespa-documentation-search/access-log-lambda/index.js
=> Make runnable for Vespa Cloud app

model-evaluation/README.md
@kkraune Please review and merge.
=> Fix doc testing in model-evaluation sample

vespa-cloud/vespa-documentation-search/access-log-lambda/README.md
=> reformat, isolate aws cli steps as optional

incremental-search/search-suggestions/src/main/application/schemas/term.sd, incremental-search/search-suggestions/src/main/application/services.xml, incremental-search/search-suggestions/src/main/java/ai/vespa/example/searchsuggest/QueryDocumentProcessor.java
=> Add mode index and accepted-check

incremental-search/search-suggestions/README.md, incremental-search/search-suggestions/count_terms.py, incremental-search/search-suggestions/example_feed.json
=> Clean up term id

vespa-cloud/vespa-documentation-search/access-log-lambda/README.md, vespa-cloud/vespa-documentation-search/access-log-lambda/index.js
=> make lambda run on all logs from yesterday

incremental-search/search-suggestions/README.md, incremental-search/search-suggestions/accepted_words.py
=> Add changes to README

vespa-cloud/vespa-documentation-search/access-log-lambda/README.md, vespa-cloud/vespa-documentation-search/access-log-lambda/index.js
=> Chunnoo/lambda fix for production logs MERGEOK

incremental-search/search-suggestions/README.md
=> Improve auto testing

vespa-cloud/vespa-documentation-search/src/main/application/services.xml, vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/docsearch/DocumentationSearcher.java
=> Add searcher for documentation

vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/docsearch/DocumentationSearcher.java
=> Fix stemming

news/bin/download-mind.sh
Fix for https://github.com/vespa-engine/vespa/issues/18611
=> Update URL of demo dataset

tensor-playground/src/main/java/ai/vespa/example/playground/ExpressionEvaluator.java
@kkraune Please review and merge. Fixes a bug in tensor expression parsing.
=> Fix tensor parsing with type

vespa-cloud/vespa-documentation-search/src/main/application/schemas/term.sd, vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/docsearch/DocumentationSearcher.java
=> Add term_array in schema MERGEOK

vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/playground/TensorPlaygroundHandler.java
@kkraune Please review. Server side of https://github.com/vespa-engine/documentation/pull/1415
=> Tensor playground: post as form, not json body to avoid preflight

vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/playground/TensorPlaygroundHandler.java
Reverts vespa-engine/sample-apps#685
@kkraune Please merge.
=> Revert "Tensor playground: post as form, not json body to avoid preflight"

vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/playground/TensorPlaygroundHandler.java
Reverts vespa-engine/sample-apps#686
@kkraune Please merge.
=> Revert "Revert "Tensor playground: post as form, not json body to avoid preflight""

vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/playground/ExpressionEvaluator.java
=> Playground: properly escape string literals for errors

vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/playground/ProtonExpressionEvaluator.java, vespa-cloud/vespa-documentation-search/src/main/java/ai/vespa/cloud/playground/TensorPlaygroundHandler.java
=> Use vespa-eval-expr in tensor playground

vespa-cloud/joins/src/main/java/ai/vespa/example/joins/DataGenerator.java, vespa-cloud/joins/src/main/java/ai/vespa/example/joins/Intersector.java, vespa-cloud/joins/src/test/java/ai/vespa/example/joins/IntersectorTest.java
@bratseth or @jobergum 
Also adding intersection for overlapping sets of intervals. It's not clear we won't need this.
=> Interval intersections

vespa-cloud/joins/src/main/application/schemas/base.sd, vespa-cloud/joins/src/main/application/schemas/tag.sd, vespa-cloud/joins/src/main/application/schemas/title.sd, vespa-cloud/joins/src/main/application/search/query-profiles/default.xml
Unable to define the document-summary in base class and inherit in concrete types (title and tag) 
=> Allow more hits from backends + btree (fast-search)

vespa-cloud/joins/src/main/java/ai/vespa/example/joins/DataGenerator.java, vespa-cloud/joins/src/main/java/ai/vespa/example/joins/Intersector.java, vespa-cloud/joins/src/test/java/ai/vespa/example/joins/IntersectorTest.java
@bratseth or @jobergum please review.
This allows efficient intersection of arbitrary sets of intervals, as long as they're each sorted by increasing start time.
=> More general intersection (no disjoint requirement)

vespa-cloud/joins/src/main/java/ai/vespa/example/joins/JoinSearcher.java, vespa-cloud/joins/src/test/java/ai/vespa/example/joins/JoinSearcherTest.java
@bratseth or @jobergum please review.
=> Add variants for joining with OR-ed ranges, or in container

model-evaluation/README.md
=> Demonstrate short form input for model-evaluation REST API

transformers/src/main/application/schemas/msmarco.sd
@jobergum Please review.
@bratseth FYI.
=> Use transformer helper functions in transformer sample app

msmarco-ranking/passage-ranking.md, msmarco-ranking/src/main/application/search/query-profiles/dense-colbert-container-rerank.xml, msmarco-ranking/src/main/bash/download_models.sh, msmarco-ranking/src/main/java/ai/vespa/searcher/QueryEncodingSearcher.java, msmarco-ranking/src/main/java/ai/vespa/searcher/QueryTensorInput.java, msmarco-ranking/src/main/java/ai/vespa/searcher/ReRankingSearcher.java, msmarco-ranking/src/test/java/ai/vespa/searcher/QueryTensorInputTest.java, msmarco-ranking/src/test/java/ai/vespa/searcher/ReRankingSearcherTest.java, msmarco-ranking/src/test/java/ai/vespa/searcher/TokenizerFactory.java
- Handle illegal max sequence input lengths
- Trim input to max sequence length determined by batch of hits that is reranked. 
- Simplify documentation, less fluff and address review comments
=> Address review comments and more

msmarco-ranking/colbert-performance-scaling.md, msmarco-ranking/passage-ranking.md, test/_test_config.yml
=> Enable document testing of passage-ranking

model-evaluation/README.md
@kkraune of @jobergum Please review.
Causes this command to hang.
=> Remove extra tick in curl command

msmarco-ranking/passage-ranking.md
=> Try to get doc testing to work

test/pseudo_terminal.py, test/test.py
@kkraune @jobergum Please review.
Mirroring https://github.com/vespa-engine/documentation/pull/1445
=> Add expect command type to documentation testing

msmarco-ranking/passage-ranking.md
=> Wait for relevancy to be right

screwdriver.yaml
=> Add zstd dependency for sample app testing which uses zstd

msmarco-ranking/src/main/java/ai/vespa/searcher/RetrievalModelSearcher.java, msmarco-ranking/src/test/java/ai/vespa/searcher/RetrievalSearcherTest.java
Plus add some comments on stemming happening in downstream searcher
=> Use language from query when tokenizing query

dense-passage-retrieval-with-ann/README.md, dense-passage-retrieval-with-ann/bin/make-vespa-feed.py, msmarco-ranking/document-ranking.md
=> Sample app - shaping up 

operations/multinode-HA/README.md
... still work in progress but a little better
=> Improve the sample app

album-recommendation-java/pom.xml, album-recommendation-monitoring/album-recommendation-random-data/pom.xml, boolean-search/pom.xml, dense-passage-retrieval-with-ann/pom.xml, dense-passage-retrieval-with-ann/src/test/java/ai/vespa/processor/QADocumentProcessorTest.java, generic-request-processing/pom.xml, http-api-using-request-handlers-and-processors/pom.xml, incremental-search/search-as-you-type/pom.xml, incremental-search/search-suggestions/pom.xml, model-evaluation/pom.xml, msmarco-ranking/pom.xml, news/app-6-recommendation-with-searchers/pom.xml, news/app-7-parent-child/pom.xml, pom.xml, tensor-playground/pom.xml, text-search/pom.xml, transformers/pom.xml, use-case-shopping/pom.xml, vespa-chinese-linguistics/pom.xml, vespa-cloud/document-processing/src/test/java/ai/vespa/example/album/ProductTypeRefinerDocProcTest.java, vespa-cloud/document-processing/src/test/java/ai/vespa/example/album/ProductTypeTokenizerDocProcTest.java, vespa-cloud/vespa-documentation-search/src/test/java/ai/vespa/cloud/docsearch/VespaDocLinksTest.java
=> Jdk17 preparations

text-video-search/README.md
=> Small fix on README

text-image-search/README.md, text-image-search/src/python/README.md
@kkraune @thigm85 Please review.
=> Update READMEs of text-image sample app

text-image-search/README.md
=> Fix minor typo in install instructions

vespa-cloud/vespa-documentation-search/src/test/application/tests/system-tests/feed-and-search-test.json
... this worked in my local test
=> Add sample test file

model-evaluation/pom.xml, model-evaluation/src/main/java/ai/vespa/example/MyHandler.java, model-evaluation/src/test/java/ai/vespa/example/MyHandlerTest.java, model-evaluation/src/test/java/ai/vespa/example/MySearcherTest.java
DO NOT MERGE. Depends on https://github.com/vespa-engine/vespa/pull/20515
FYI: @lesters, @kkraune, @bratseth
=> Use ThreadedHttpRequestHandler

news/app-6-recommendation-with-searchers/src/main/application/services.xml, news/app-7-parent-child/src/main/application/services.xml
=> Fix bundle names in news recommendation tutorial sample app

dense-passage-retrieval-with-ann/src/main/application/schemas/wiki.sd
=> Use Transformer convenience functions

model-evaluation/src/main/java/ai/vespa/example/MyHandler.java, model-evaluation/src/test/java/ai/vespa/example/MyHandlerTest.java
Reverting for now, as the sample app build fails.
=> Revert "Use ThreadedHttpRequestHandler instead of LoggingRequestHandler"

vespa-cloud/album-recommendation-java/src/main/application/deployment.xml, vespa-cloud/album-recommendation-prod-tests/deployment.xml, vespa-cloud/album-recommendation/src/main/application/deployment.xml, vespa-cloud/cord-19-search/deployment.xml, vespa-cloud/cord-19-search/src/main/application/deployment.xml, vespa-cloud/joins/src/main/application/deployment.xml, vespa-cloud/vespa-documentation-search/src/main/application/deployment.xml
=> Remove deprecated attribute

model-evaluation/src/main/java/ai/vespa/example/MyHandler.java, model-evaluation/src/test/java/ai/vespa/example/MyHandlerTest.java
=> Use threaded http request handler take2

news/src/python/user_search.py
... or @bjormel 
(need this to fix automated testing, will revert later)
=> Temporarily add tracing for debugging

news/src/python/user_search.py
Reverts vespa-engine/sample-apps#782
=> Revert "Temporarily add tracing for debugging"

http-api-using-request-handlers-and-processors/src/main/java/com/mydomain/demo/DemoHandler.java
=> Preserve metrics from custom handler

vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/FeedAndSearchSystemTest.java, vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/StagingCommons.java, vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/StagingSetupTest.java, vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/StagingVerificationTest.java
Reverts vespa-engine/sample-apps#777
=> Revert "Use feed client"

vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/FeedAndSearchSystemTest.java, vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/StagingCommons.java, vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/StagingSetupTest.java, vespa-cloud/album-recommendation-java/src/test/java/ai/vespa/example/album/StagingVerificationTest.java
Reverts vespa-engine/sample-apps#785
=> Use feed client

msmarco-ranking/src/main/python/model-exporting.ipynb
=> unbreak usage of transformers.pipeline after api changes

vespa-cloud/cord-19-search/src/main/application/services.xml, vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/BoldingSearcher.java, vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedArticlesByNNSearcher.java, vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/cord19/searcher/RelatedArticlesSearcher.java, vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/docproc/BERTProcessor.java, vespa-cloud/cord-19-search/src/main/java/ai/vespa/example/tokenizer/BertTokenizer.java, vespa-cloud/cord-19-search/src/test/java/ai/vespa/example/cord19/searcher/BoldingSearcherTest.java
Also, some non-functional cleanup.
=> Don't inject SimpleLinguistics, it's not a component

album-recommendation-java/pom.xml, album-recommendation-monitoring/album-recommendation-random-data/pom.xml, pom.xml, text-image-search/pom.xml, vespa-chinese-linguistics/pom.xml, vespa-cloud/album-recommendation-prod-tests/pom.xml
=> Add all Java sample apps to aggregator pom

album-recommendation-monitoring/album-recommendation-random-data/src/main/java/application/VespaDataFeeder.java
=> Constructor signature has changed

vespa-chinese-linguistics/src/main/java/com/qihoo/language/JiebaLinguistics.java
=> Linguistics interface added a new method since previous release

album-recommendation-monitoring/album-recommendation-random-data/pom.xml, album-recommendation-monitoring/album-recommendation-random-data/src/main/java/application/VespaDataFeeder.java, album-recommendation-monitoring/album-recommendation-random-data/src/main/java/application/VespaQueryFeeder.java
=> Use vespa-feed-client in album-recommendation-random-data

boolean-search/README.md
=> Use vespa-feed-client in boolean-search sample app

screwdriver.yaml
=> Install unzip from yum

dense-passage-retrieval-with-ann/README.md, incremental-search/search-suggestions/README.md, model-evaluation/README.md, msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md, part-purchases-demo/README.md, semantic-qa-retrieval/README.md, transformers/README.md, use-case-shopping/README.md, vespa-cloud/cord-19-search/experiment-yourself.md, vespa-cloud/cord-19-search/feeding.md, vespa-cloud/vespa-documentation-search/README.md
=> Use vespa-feed-client in remaining sample apps

pom.xml
=> Module is moved

test/_test_config.yml
... or @hmusum - screwdriver still fails
Keeping the shrinked containers though, I will add to guide that these are not prod settings
=> Remove multinode testing, no capacity

operations/multinode/README.md, operations/multinode/src/main/application/services.xml, test/_test_config.yml
=> Run with less resources for auto test

screwdriver.yaml
=> use max screwdriver resources

test/_test_config.yml
- now using highest possible screwdriver resources
... or @hmusum 
The good news is, the regular multinode test works well in automated testing :-)
=> Test multinode-HA

screwdriver.yaml, test/_test_config.yml
- leave manually tested for now, I did not find a good workaround
=> non-verbose, do not test multinode-HA

transformers/README.md, transformers/src/python/setup-model.py
https://github.com/vespa-engine/vespa/issues/20893
=> Fix for update transformer api

operations/album-recommendation-monitoring/docker-compose.yml
=> Remove version for compatibility

use-case-shopping/src/main/java/ai/vespa/example/shopping/ReviewProcessor.java, vespa-cloud/joins/src/main/java/ai/vespa/example/joins/JoinSearcher.java
=> Update deprecated feature

operations/album-recommendation-monitoring/album-recommendation-random-data/Dockerfile
=> Less build output

vespa-cloud/album-recommendation/src/test/application/tests/staging-setup/feed-without-stemming.json, vespa-cloud/album-recommendation/src/test/application/tests/staging-test/query-and-update-with-stemming.json
@havardpe please review. Does this make sense?
=> Make staging test work by default, and hint at how it could fail

use-case-shopping/README.md
=> fix format failing sample apps verify pipeline

screwdriver.yaml
=> Add vespa-cli

text-image-search/src/python/README.md, use-case-shopping/src/main/application/services.xml
=> fix link and remove remote debug options

screwdriver.yaml
=> Build curl

screwdriver.yaml
=> update path - why

screwdriver.yaml
=> Attempt #10002

screwdriver.yaml
=> Revert all of this, not able to use vespa-cli on centos7

msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md
=> models dir needs to be created

msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md
=> formatting and download models first

screwdriver.yaml
=> Try to install vespa-cli

screwdriver.yaml
- the build never worked with ubuntu, use image from quickstart guide ...
=> Use buildpack-deps

msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md, text-image-search/README.md, text-image-search/src/python/README.md, text-video-search/README.md, use-case-shopping/README.md
=> Move to sample-apps-data folder in S3 bucket

msmarco-ranking/document-ranking.md
=> use correct urls

dense-passage-retrieval-with-ann/src/test/application/tests/system-test/passage-ranking-system-test.json
=> Remove extra ,

test/_test_config_new.yml
=> Add text-image-search to tested app

text-image-search/pom.xml, text-image-search/src/sh/download_onnx_model.sh
=> Download model from s3 before build and unit testing

screwdriver.yaml
=> Try running mvn build with larger heap

screwdriver.yaml
=> Hit me one more time

screwdriver.yaml
=> Then we try MAVEN_OPTS

examples/operations/basic-search-on-gke/README.md, examples/operations/multinode-HA/README.md, examples/operations/multinode/README.md, examples/operations/secure-vespa-with-mtls/README.md
=> Fix relative path for examples

screwdriver.yaml
=> Double timeout, run once a day

examples/boolean-search/README.md, examples/operations/multinode-HA/README.md, examples/operations/multinode/README.md, incremental-search/search-suggestions/README.md, vespa-cloud/vespa-documentation-search/README.md
=> More readable queries

.gitignore, _plugins-linkcheck/vespa_xml_links_generator.rb, screwdriver.yaml
FYI @bratseth 
This should find some broken links, lets validate that and fix separately
=> First cut link checking in app package files

text-image-search/README.md, text-image-search/src/main/java/ai/vespa/example/TextEmbeddingSearcher.java
=> Fix mvn build issue with test guide + input validation 

screwdriver.yaml
=> Use TURBO for build - job gets killed

model-evaluation/README.md, model-evaluation/src/test/application/tests/system-tests/model-evaluation-test.json, text-search/README.md, transformers/src/test/application/tests/system-test/document-ranking-test.json
Also fix failing transformer system test, plus some links :)
=> Add system tests 

model-evaluation/src/main/application/services.xml, model-evaluation/src/test/application/tests/system-tests/model-evaluation-test.json, text-image-search/src/main/application/services.xml, transformers/src/test/application/tests/system-test/document-ranking-test.json
=> Fix test (again) and make endpoint names shorter by using default as container name MERGEOK

model-evaluation/README.md, transformers/README.md
=> Jobergum/move to vespa curl MERGEOK

incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md
=> Try to fix test failures

incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md, use-case-shopping/README.md
=> Attempt to fix test #2 

test/_test_config_new.yml
=> Update _test_config_new.yml MERGEOK

screwdriver.yaml
=> Reducing to HIGH

screwdriver.yaml
Reverts vespa-engine/sample-apps#923
=> Revert "Reducing to HIGH"

screwdriver.yaml, test/_test_config.yml, test/_test_config_big.yml
- also try HIGH for building, should be sufficient
=> Separate BIG build job

test/_test_config.yml, test/_test_config_big.yml
=> Split to reduce overall duration

examples/operations/multinode-HA/src/main/application/services.xml
- multinode-HA test works fine with this - thanks @hmusum
=> Use less memory for cluster-controllers

dense-passage-retrieval-with-ann/src/test/java/ai/vespa/processor/QADocumentProcessorTest.java, examples/document-processing/src/main/java/ai/vespa/example/album/DocTypeDocumentProcessor.java, examples/document-processing/src/test/java/ai/vespa/example/album/DocTypeDocProcTest.java, examples/document-processing/src/test/java/ai/vespa/example/album/ProductTypeRefinerDocProcTest.java, examples/document-processing/src/test/java/ai/vespa/example/album/ProductTypeTokenizerDocProcTest.java, incremental-search/search-as-you-type/pom.xml, incremental-search/search-as-you-type/src/main/application/services.xml, msmarco-ranking/src/test/java/ai/vespa/docproc/DenseDocumentEmbedderTest.java, msmarco-ranking/src/test/java/ai/vespa/docproc/DocumentTensorizerTest.java
=> Move away from deprecated and removed apis

screwdriver.yaml
- it builds fine without on my laptop, lets try without
=> remove un-needed args

dense-passage-retrieval-with-ann/README.md, incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md, model-evaluation/README.md, msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md, test/_test_config.yml, text-image-search/README.md, transformers/README.md, use-case-shopping/README.md
=> try make test work + auth login

examples/generic-request-processing/pom.xml, examples/http-api-using-request-handlers-and-processors/pom.xml, examples/multiple-bundles-lib/pom.xml, examples/multiple-bundles/pom.xml, examples/predicate-fields/pom.xml
=> Remove jdkToolchain, only relevant with maven-toolchains-plugin

screwdriver.yaml, text-image-search/README.md
=> remove temp log dump

msmarco-ranking/passage-ranking.md, screwdriver.yaml
=> Add data test for notebook execution + enable PR testing

news/app-2-feed-and-query/schemas/news.sd, news/app-3-searching/schemas/news.sd, news/app-5-recommendation/schemas/news.sd, news/app-6-recommendation-with-searchers/src/main/application/schemas/news.sd, news/app-7-parent-child/src/main/application/schemas/news.sd
=> add fast-search to date field MERGEOK

msmarco-ranking/passage-ranking.md, screwdriver.yaml, test/_test_config.yml, test/_test_config_big.yml, test/test.py
Try to fix this, most likely caused by installing pytest using --user 
```
********************************************************************************
08:35:26 * pytest --nbmake src/main/python/model-exporting.ipynb
08:35:26 * (Expecting '1 passed')
08:35:26 ********************************************************************************
08:35:26 /bin/sh: 36: pytest: not found
08:35:26 sentinel-224050> exit code: 127
08:35:26 
08:35:26 ERROR: Expected output '1 passed' not found in command 'pytest --nbmake src/main/python/model-exporting.ipynb'
```
=> Use module support instead MERGEOK

test/_test_config.yml, text-search/README.md, text-search/src/main/application/schemas/msmarco.sd, text-search/src/main/application/services.xml
The tests present in the https://github.com/vespa-engine/documentation/blob/master/en/tutorials/text-search.md does not test the end to end app. 
=> end to end not tested in doc MERGEOK

text-search/README.md
=> delete correct container MERGEOK

examples/operations/multinode-HA/README.md
=> Ports and mappings

examples/operations/README.md
=> link to arm preview

examples/operations/multinode-HA/README.md, examples/operations/multinode-HA/pki/client/.gitignore, examples/operations/multinode-HA/pki/vespa/.gitignore, examples/operations/multinode-HA/scripts/generate-cert-chains.sh, examples/operations/multinode-HA/scripts/generate-client-cert-chain.sh, examples/operations/multinode-HA/scripts/generate-vespa-cert-chain.sh, examples/operations/multinode-HA/services.xml.secure, examples/operations/multinode-HA/tls/.gitignore, examples/operations/multinode-HA/tls/tls.json
- not tested yet, want to get this in for a new manual test, works locally
- will remove the mtls sample and move some files here once done
=> First cut mTLS for multinode-HA

billion-scale-vector-search/README.md
=> Add link to blog post MERGEOK

examples/generic-request-processing/pom.xml, examples/http-api-using-request-handlers-and-processors/pom.xml, examples/operations/album-recommendation-monitoring/album-recommendation-random-data/pom.xml, examples/predicate-fields/pom.xml
This is all we have for sample-apps
=> Set release 17 MERGEOK

screwdriver.yaml
- lets try a PR build first ...
=> Define dependencies once

billion-scale-vector-search/README.md, dense-passage-retrieval-with-ann/README.md, incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md, model-evaluation/README.md, msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md, text-image-search/README.md, transformers/README.md, use-case-shopping/README.md
=> Stop using deprecated command

billion-scale-vector-search/README.md, dense-passage-retrieval-with-ann/README.md, examples/vespa-chinese-linguistics/README.md, incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md, model-evaluation/README.md, msmarco-ranking/document-ranking.md, msmarco-ranking/passage-ranking.md, text-image-search/README.md, text-search/README.md, transformers/README.md, use-case-shopping/README.md
=> Moved to Java 17

test/_test_config_big.yml
=> Reorder tests

billion-scale-vector-search/src/main/application/cloud-services.xml
=> Move license into <xml> tag

msmarco-ranking/passage-ranking.md
We should find a way to link to common dependencies/prereqs @kkraune
=> Wrong Java version

news/src/python/create_bert_embeddings.py
=> Silence unneccesary warnings when training model

album-recommendation/tests/staging-setup/feed-without-stemming.json, album-recommendation/tests/staging-test/query-and-update-with-stemming.json
@hakonhall please review. Thought I did this half a year ago, but apparently not the case :O
=> Make test pass when not modified

examples/operations/album-recommendation-monitoring/album-recommendation-random-data/src/main/java/ai/vespa/examples/application/VespaDataFeeder.java, examples/operations/album-recommendation-monitoring/album-recommendation-random-data/src/main/java/ai/vespa/examples/application/VespaQueryFeeder.java
=> Use vespa-container

billion-scale-vector-search/README.md
=> Download latest vespa-feed-client-cli version

msmarco-ranking/document-ranking-README.md
- Fix the test and use vespa-cli for readability
=> Fix test after removing a directory

msmarco-ranking/src/main/bash/download_models.sh, msmarco-ranking/src/test/java/ai/vespa/examples/docproc/ColBERTDocumentProcessorTest.java
=> download correct model

screwdriver.yaml, test/_test_config_big.yml
- If this works, we will have one verify-* job for all the small ones and separate jobs for the jumbos (Next PR - let's test this first)
=> Run huge sample-app testing separately

README.md
=> Add link to new sample app from main readme

commerce-product-ranking/README.md, commerce-product-ranking/application/tests/system-test/feed-and-search-test.json
=> fix test and add link to blog

commerce-product-ranking/README.md, commerce-product-ranking/application/schemas/product.sd, commerce-product-ranking/application/services.xml, commerce-product-ranking/notebooks/train_neural.ipynb, commerce-product-ranking/scripts/evaluate.py, commerce-product-ranking/scripts/export-bi-encoder.py, commerce-product-ranking/scripts/export-cross-encoder.py
=> Update sample app with neural methods

commerce-product-ranking/notebooks/train_neural.ipynb
=> More comments in notebook

commerce-product-ranking/README.md
=> improve readme

msmarco-ranking/src/main/java/ai/vespa/examples/docproc/ColBERTDocumentProcessor.java, msmarco-ranking/src/test/java/ai/vespa/examples/docproc/ColBERTDocumentProcessorTest.java
=> Use correct max length

examples/predicate-fields/README.md
- fixes feed client download + typos / format / language
=> Kkraune/predicate readme MERGEOK

examples/predicate-fields/README.md
=> Add exec test MERGEOK

examples/predicate-fields/README.md
=> wait for start

examples/predicate-fields/README.md
=> Alice and Bob

billion-scale-image-search/src/main/java/ai/vespa/examples/docproc/AssignCentroidsDocProc.java
=> Use timeout from processing

billion-scale-image-search/src/main/java/ai/vespa/examples/docproc/AssignCentroidsDocProc.java
Reverts vespa-engine/sample-apps#1097
=> Revert "Use timeout from processing"

billion-scale-image-search/README.md
=> Escape html characters in '<pre>' block

incremental-search/search-suggestions/README.md
=> userInput and userQuery, annotation, performance

incremental-search/search-suggestions/README.md
=> fix userInput

simple-semantic-search/README.md, simple-semantic-search/export_model_from_hf.py
Maybe we can drop the onnx file now? 
=> Add details on how to export a model

billion-scale-vector-search/src/main/java/ai/vespa/examples/docproc/AssignNeighborsDocProc.java
=> Improve timeout logic by using Processing.timeLeft()

examples/aws/lambda/README.md, examples/aws/lambda/hello_function.py, examples/google-cloud/cloud-functions/README.md, examples/google-cloud/cloud-functions/main.py, examples/google-cloud/cloud-functions/requirements.txt
- This is the start of a set of examples with script code to work with Vespa artifacts in AWS/GCP
=> Add AWS / Google Cloud examples

commerce-product-ranking/scripts/evaluate.py
=> Testing in constrained environments with cold starts

examples/aws/lambda/hello_function.py, examples/google-cloud/cloud-functions/README.md, examples/google-cloud/cloud-functions/go/function.go, examples/google-cloud/cloud-functions/go/visit.go
- this just counts number of docs - add storage option later
- based on @arnej27959 's code for the Vespa CLI
=> Proof of Concept: Add WIP visit code

simple-semantic-search/schemas/doc.sd
=> Add cosine example

use-case-shopping/src/main/application/schemas/query.sd
=> Add query schema

commerce-product-ranking/README.md
=> Add links to post 3

use-case-shopping/src/main/java/ai/vespa/example/shopping/site/view/ItemRenderer.java
=> change to render stars

use-case-shopping/create_suggestions.py, use-case-shopping/src/main/application/schemas/query.sd, use-case-shopping/src/main/application/services.xml, use-case-shopping/src/main/java/ai/vespa/example/shopping/SuggestionSearcher.java, use-case-shopping/src/main/resources/site/css/site.css, use-case-shopping/src/main/resources/site/js/autocomplete.js, use-case-shopping/src/main/resources/templates/header.html.template, use-case-shopping/src/main/resources/templates/search.html.template
=> Better auto-complete, nicer searcher box

use-case-shopping/src/main/java/ai/vespa/example/shopping/site/data/SearchResults.java
=> Handle empty input

use-case-shopping/src/main/java/ai/vespa/example/shopping/site/data/SearchResults.java
=> fix category navigation with empty query

use-case-shopping/src/main/java/ai/vespa/example/shopping/site/data/SearchResults.java
=> One must handle quotes in the input for phrase search support MERGEOK

use-case-shopping/src/main/application/schemas/item.sd
=> Drop documents with too low semantic score if keyword score is 0

dense-passage-retrieval-with-ann/README.md, dense-passage-retrieval-with-ann/bin/export-reader-model.py, dense-passage-retrieval-with-ann/requirements.txt
=> try pinning onnxruntime

use-case-shopping/src/main/application/schemas/item.sd, use-case-shopping/src/main/java/ai/vespa/example/shopping/site/data/SearchResults.java, use-case-shopping/src/main/java/ai/vespa/example/shopping/site/view/SearchRenderer.java
=> Handle phrase quotes and filter properly as cosine might be negative

use-case-shopping/src/main/java/ai/vespa/example/shopping/site/data/SearchResults.java
=> don't require all terms

use-case-shopping/src/main/application/schemas/item.sd
=> Change filtering

screwdriver.yaml
=> Add verbose to understand deploy failure

dense-passage-retrieval-with-ann/README.md, dense-passage-retrieval-with-ann/bin/export-query-model.py, dense-passage-retrieval-with-ann/bin/export-reader-model.py, dense-passage-retrieval-with-ann/requirements.txt
=> update to include quantization

examples/google-cloud/cloud-functions/README.md, examples/google-cloud/cloud-functions/go/go.mod, examples/google-cloud/cloud-functions/go/visit.go
- this works but needs some more sanding before it is a good example ...
=> First cut backup sample code

test/_test_config.yml
=> Add to test

multi-vector-indexing/README.md
=> Add link to blog post.

transformers/README.md, transformers/src/main/application/schemas/msmarco.sd
=> Re-rank with transformer model at global-phase

commerce-product-ranking/README.md, commerce-product-ranking/application/schemas/product.sd
=> Re-rank with cross-encoder at global-phase

feed-split.py
=> Remove images from paragraph index

billion-scale-image-search/src/main/python/create-joined-feed.py
127 is max value for this field
=> Cap similarity at max byte value 127

news/bin/download-mind.sh
@kkraune or @jobergum please review
=> remove "-nd" option intended for wget

news/app-5-recommendation/schemas/news.sd, news/app-5-recommendation/schemas/user.sd, news/app-5-recommendation/search/query-profiles/types/root.xml, news/app-6-recommendation-with-searchers/src/main/application/schemas/news.sd, news/app-6-recommendation-with-searchers/src/main/application/schemas/user.sd, news/app-6-recommendation-with-searchers/src/main/application/search/query-profiles/types/root.xml, news/app-7-parent-child/src/main/application/schemas/news.sd, news/app-7-parent-child/src/main/application/schemas/user.sd, news/app-7-parent-child/src/main/application/search/query-profiles/types/root.xml, news/src/python/convert_embeddings_to_vespa_format.py
@jobergum or @lesters please review
=> update "news" sample apps to use "dotproduct" distance metric

commerce-product-ranking/application/services.xml, custom-embeddings/services.xml, multi-vector-indexing/services.xml, simple-semantic-search/services.xml, use-case-shopping/src/main/application/services.xml
Reverts vespa-engine/sample-apps#1208
=> Revert "Use new syntax for Bert embedder"

album-recommendation-java/pom.xml, billion-scale-image-search/pom.xml, billion-scale-vector-search/pom.xml, dense-passage-retrieval-with-ann/pom.xml, examples/document-processing/pom.xml, examples/generic-request-processing/pom.xml, examples/joins/pom.xml, examples/multiple-bundles-lib/src/main/java/ai/vespasamples/lib/FibonacciProducer.java, examples/multiple-bundles-lib/src/main/java/ai/vespasamples/lib/package-info.java, examples/multiple-bundles/pom.xml, examples/multiple-bundles/src/main/application/services.xml, examples/multiple-bundles/src/main/java/ai/vespasamples/search/FibonacciSearcher.java, examples/multiple-bundles/src/test/java/ai/vespasamples/ApplicationMain.java, examples/predicate-fields/pom.xml, incremental-search/search-as-you-type/pom.xml, incremental-search/search-suggestions/pom.xml, model-inference/pom.xml, msmarco-ranking/pom.xml, news/app-6-recommendation-with-searchers/pom.xml, news/app-7-parent-child/pom.xml, text-image-search/pom.xml, text-search/pom.xml, use-case-shopping/pom.xml
The feature is included in 8.172
=> Fail on warnings from bundle plugin

commerce-product-ranking/application/services.xml, custom-embeddings/services.xml, multi-vector-indexing/services.xml, simple-semantic-search/services.xml, use-case-shopping/src/main/application/services.xml
Reverts vespa-engine/sample-apps#1211
=> Revert "Revert "Use new syntax for Bert embedder""

custom-embeddings/services.xml, multi-vector-indexing/services.xml, simple-semantic-search/services.xml
=> bertbase-embedder -> bert-embedder

simple-semantic-search/README.md, simple-semantic-search/export_hf_model_from_hf.py, simple-semantic-search/export_model_from_hf.py
=> Consolidate and document

examples/embedding-service/.gitignore, examples/embedding-service/README.md, examples/embedding-service/pom.xml, examples/embedding-service/src/main/application/services.xml, examples/embedding-service/src/main/java/ai/vespa/example/embedding_service/EmbeddingHandler.java, pom.xml
=> Add embedding service sample app (WIP)

vector-streaming-search/README.md, vector-streaming-search/ext/docs.json, vector-streaming-search/schemas/mail.sd, vector-streaming-search/services.xml
=> Create sample app for vector streaming search.

incremental-search/search-suggestions/README.md
@kkraune or @geirst please merge
=> Correct link

vector-streaming-search/README.md
@bratseth or @kkraune please review
=> Add version and link to blog post.

vector-streaming-search/README.md
@bratseth or @kkraune please review and merge
=> Update Vespa version.

custom-embeddings/services.xml
=> fix config

multilingual-search/README.md
=> Install deps + spelling

examples/embedder-auto-training-evaluation/application-package/schemas/doc.sd, examples/embedder-auto-training-evaluation/query-generation/generate_gpt_queries.ipynb, examples/embedder-auto-training-evaluation/train_and_evaluate.sh
=> Rename ranking profile

examples/embedder-auto-training-evaluation/README.md, examples/embedder-auto-training-evaluation/scripts/positives-negatives.py, examples/embedder-auto-training-evaluation/scripts/sentence-transformers.py, examples/embedder-auto-training-evaluation/train_and_evaluate.sh
=> Use our own training script with SentenceTransformers to train models, instead of SimLM

dense-passage-retrieval-with-ann/requirements.txt
Reverts vespa-engine/sample-apps#1246
=> Revert "Update dependency torch to v1.13.1 [SECURITY]"

renovate.json
Require approval from dashboard for PR creation
=> Update renovate.json MERGEOK

renovate.json
=> Ignore false positive

examples/generic-request-processing/pom.xml, examples/http-api-using-request-handlers-and-processors/pom.xml, examples/multiple-bundles-lib/pom.xml, examples/multiple-bundles/pom.xml, examples/predicate-fields/pom.xml, examples/vespa-chinese-linguistics/pom.xml
Reverts vespa-engine/sample-apps#1292
FYI @baldersheim
=> Revert "Update dependency org.junit.jupiter:junit-jupiter to v5.10.0" MERGEOK

examples/generic-request-processing/pom.xml, examples/http-api-using-request-handlers-and-processors/pom.xml, examples/multiple-bundles-lib/pom.xml, examples/multiple-bundles/pom.xml, examples/predicate-fields/pom.xml, examples/vespa-chinese-linguistics/pom.xml
@baldersheim please review
@kkraune @gjoranv @aressem FYI
=> use current junit.vespa.version (5.8.1) MERGEOK

commerce-product-ranking/README.md, multilingual-search/README.md
=> Use latest tag of trac_eval. Default branch has broken code.

examples/model-deployment/ONNXModelExport.ipynb
=> Specify execution provider in onnx inference session

screwdriver.yaml
- fix the last linkcheck failures
=> follow redirects for link check

examples/lucene-linguistics/README.md, examples/lucene-linguistics/advanced-configuration/pom.xml, examples/lucene-linguistics/going-crazy/pom.xml, examples/lucene-linguistics/minimal/pom.xml, examples/lucene-linguistics/non-java/README.md
The latest updates to the Lucene linguistics are pretty significant.
=> Update dependencies for Lucene Linguistics demos

_config.yml, _paragraphs_config.yml, _suggestions_config.yml
=> Feed to enclave

examples/operations/multinode-HA/README.md
=> Add Vespa CLI TLS examples MERGEOK

renovate.json
=> Ignore Vespa deps

renovate.json
Reverts vespa-engine/sample-apps#1333
=> Revert "Ignore Vespa deps"

dense-passage-retrieval-with-ann/requirements.txt
Reverts vespa-engine/sample-apps#1344
=> Revert "Update dependency onnxruntime to v1.16.1"

dense-passage-retrieval-with-ann/requirements.txt
=> attempt to relax pb version?

screwdriver.yaml
=> Another day another python dep issue

screwdriver.yaml
=> Use AlmaLinux for pipelines.

billion-scale-vector-search/README.md
Not sure if it captures the same queries and the ground truth in the competition, but it's worth a try. If not, we have to re-do this work.
=> Try with different query file

colbert/.gitignore, colbert/README.md, colbert/ext/1.json, colbert/ext/2.json, colbert/ext/3.json, colbert/schemas/doc.sd, colbert/services.xml, simple-semantic-search/README.md, simple-semantic-search/schemas/doc.sd, simple-semantic-search/services.xml
=> Add colbert sample app and re-factor simple-semantic-search

test/_test_config.yml
=> Add colbert sample app to testing

colbert/schemas/doc.sd
=> Fix spacing

billion-scale-image-search/README.md, billion-scale-vector-search/README.md, dense-passage-retrieval-with-ann/README.md, examples/predicate-fields/README.md, examples/vespa-chinese-linguistics/README.md, incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md, model-inference/README.md, msmarco-ranking/document-ranking-README.md, msmarco-ranking/passage-ranking-README.md, text-image-search/README.md, text-search/README.md, use-case-shopping/README.md
=> data-proofer-ignore openjdk.org links

colbert-long/README.md, colbert-long/services.xml, colbert/README.md, colbert/services.xml
=> fix sample app and add link MERGEOK

text-video-search/src/python/create-feed-query-text-video-search.ipynb, text-video-search/src/python/embedding.py, text-video-search/src/python/requirements.txt
Also, a bit of formatting diffs in the notebook, due to ruff. 
Did not run through the whole sample app, as it downloads ~6GB and takes a lot of time, but these changes enable the first half of the notebook to run successfully at least.
=> Updates to text-video-search sample app

billion-scale-image-search/src/main/application/schemas/image.sd, examples/joins/src/main/application/schemas/tag.sd, examples/joins/src/main/application/schemas/title.sd, multi-vector-indexing/schemas/wiki.sd, multilingual-search/schemas/doc.sd, text-search/src/main/application/schemas/msmarco.sd, use-case-shopping/src/main/application/schemas/item.sd, use-case-shopping/src/main/application/schemas/query.sd
@geirst : please review
@jobergum : FYI
=> Don't specify type for document summary.

multi-vector-indexing/schemas/wiki.sd, multilingual-search/README.md, multilingual-search/schemas/doc.sd
=> Avoid log of zero for hybrid ranking

colbert-long/services.xml, colbert/services.xml, examples/lucene-linguistics/non-java/services.xml
Try using this for a couple of the latest sample apps
=> Add minimum-required-vespa-version to a few apps

custom-embeddings/schemas/doc.sd, multilingual-search/README.md, simple-semantic-search/README.md, simple-semantic-search/export_hf_model_from_hf.py
Relates to https://github.com/vespa-engine/vespa/issues/31086 
=> Add ability to patch tokenizer.json file and include support for quantization

colbert/README.md, colbert/schemas/doc.sd, colbert/services.xml, msmarco-ranking/python/evaluate_passage_run.py, msmarco-ranking/schemas/passage.sd, msmarco-ranking/services.xml, multi-vector-indexing/README.md, multi-vector-indexing/schemas/wiki.sd, multi-vector-indexing/services.xml, multilingual-search/README.md, multilingual-search/ext/evaluate.py, multilingual-search/schemas/doc.sd, multilingual-search/services.xml, simple-semantic-search/README.md, simple-semantic-search/schemas/doc.sd, simple-semantic-search/services.xml, vector-streaming-search/README.md, vector-streaming-search/services.xml
=> Add prepend configuration and re-factor some readme query examples

multilingual-search/README.md
=> Better relevance after correct prepend instructions

retrieval-augmented-generation/services.xml
@musum or @kkraune Please review.
=> Change to phi-3 quantized model for demonstration

colbert-long/scripts/convert.py
I have Python 3.12.4, had to add this to run script successfully
=> trust_remote_code

billion-scale-image-search/src/main/bash/download_models.sh, billion-scale-vector-search/README.md, commerce-product-ranking/README.md, commerce-product-ranking/application/services.xml, commerce-product-ranking/notebooks/Train-lightgbm.ipynb, commerce-product-ranking/notebooks/Train-xgboost.ipynb, commerce-product-ranking/notebooks/train_neural.ipynb, examples/embedding-service/README.md, incremental-search/search-as-you-type/README.md, multilingual-search/services.xml, retrieval-augmented-generation/services.xml, text-image-search/README.md, text-image-search/src/python/README.md, text-image-search/src/sh/download_onnx_model.sh, text-video-search/README.md, text-video-search/src/python/app.py, use-case-shopping/README.md
=> data.vespa.oath.cloud -> data.vespa-cloud.com

.github/workflows/verify-guides-billion-image.yml, .github/workflows/verify-guides-billion-vector.yml, .github/workflows/verify-guides-main.yml
=> Giudes -> Guides

visual-retrieval-colpali/.gitignore, visual-retrieval-colpali/README.md, visual-retrieval-colpali/hello.py, visual-retrieval-colpali/pyproject.toml, visual-retrieval-colpali/uv.lock
Adds a skeleton and instructions on getting set up with environment.
cc: @andreer
=> ColPali - initialize python env

billion-scale-image-search/src/main/python/create-centroid-feed.py
Attempt to fix https://github.com/vespa-engine/sample-apps/actions/runs/10919083474/job/30305987871.
Got some formatting for free.
=> (ci) convert vector to bytes before hashing

_config.yml, _paragraphs_config.yml, _suggestions_config.yml
=> Use correct hostname

visual-retrieval-colpali/README.md
=> correct command name

visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/main.py
Some cleanup and refactoring of sim map inference so that it is done only once in a batch for all images.
=> (colpalidemo) make sim_maps more efficient

visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/colpalidemo/schemas/pdf_page.sd, visual-retrieval-colpali/deploy_vespa_app.py, visual-retrieval-colpali/feed_vespa.py, visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/main.py
Fed `full_image` field to vespa, and modified app to select that one.
=> (colpalidemo) full image size

visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/main.py
=> make radio buttons do something (and add page numbers, score)

visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/main.py
Need to handle the active sim map button not being reset on DOM update.
=> (colpalidemo) generator for sim maps

visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/colpali-with-snippets/schemas/pdf_page.sd
=> always use sim map from vespa

visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/globals.css, visual-retrieval-colpali/output.css
=> Add text-highlight

visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/frontend/app.py
This pull request includes changes to improve token filtering in the backend and enhance the display of relevance scores in the frontend.
Improvements to token filtering:
* [`visual-retrieval-colpali/backend/colpali.py`](diffhunk://#diff-9f71787d80b4b30c3fefe0bcd39c68ff141dc10c41b0380ca3b3575e0259449eR474-R476): Updated the `is_special_token` function to exclude tokens with fewer than 3 characters from the similarity map generation.
Enhancements to relevance score display:
* [`visual-retrieval-colpali/frontend/app.py`](diffhunk://#diff-fb191576cdc977b2ee2f2b490 …
=> (colpalidemo) score format and token exclude

visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/globals.css, visual-retrieval-colpali/output.css
=> Simplify spinner icon

visual-retrieval-colpali/frontend/app.py
=> Add loading spinner for tokens

visual-retrieval-colpali/main.py
=> (colpalidemo) load model on startup

visual-retrieval-colpali/README.md
=> document css build

visual-retrieval-colpali/README.md
=> (colpalidemo) add instructions to readme

visual-retrieval-colpali/README.md
=> Fix css name

visual-retrieval-colpali/frontend/app.py
=> Same style for loading icons

retrieval-augmented-generation/services.xml
=> Update local model to phi 3.5

visual-retrieval-colpali/.gitignore, visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/main.py, visual-retrieval-colpali/pyproject.toml, visual-retrieval-colpali/uv.lock
Replaced placeholders for the chat, and added inference with `gemini-1.5-flash-8b`. 
Implemented as SSE connection that streams the result as HTML async. 
##
Using this system prompt
```python
GEMINI_SYSTEM_PROMPT = """If the user query is a question, try your best to answer it based on the provided images. 
If the user query is not an obvious question, reply with 'No question detected.'. Your response should be HTML formatted.
This means that newlines will be replaced with <br> tags, bold text will be enclosed in <b> tags, and so on.
"""
```
Feel free to …
=> (colpalidemo) add gemini inference

visual-retrieval-colpali/.gitignore, visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/main.py, visual-retrieval-colpali/prepare_feed_deploy.py, visual-retrieval-colpali/requirements.txt, visual-retrieval-colpali/uv.lock
Including changes from @andreer and fixing gemini inference to run on full images (it wasn't able to answer much based on the blurred ones 😅). 
@ldalves: Modified some CSS (with ChatGPT assistance) to prevent the header (Vespa.ai + ...) from being cut off on top in HF. Please review/change if it doesn't make sense. (but it works at least).
=> (colpalidemo) consolidate updates

visual-retrieval-colpali/README.md
micro pr as I saw this after merging :)
=> remove ref to deleted file

visual-retrieval-colpali/README.md
Ref https://github.com/vespa-engine/sample-apps/pull/1525
=> Remove internal link to content removed in previous PR

visual-retrieval-colpali/backend/vespa_app.py, visual-retrieval-colpali/main.py
Set keepalive to run every 5s. Also added timeout to message-generator.
=> (colpalidemo) fix gemini timeout and keepalive

visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/globals.css, visual-retrieval-colpali/main.py, visual-retrieval-colpali/output.css
=> Add suggestions

visual-retrieval-colpali/.gitignore, visual-retrieval-colpali/main.py
=> (colpalidemo) fix update image cache bug

visual-retrieval-colpali/frontend/app.py
=> Replace "\u2581" in tokens

visual-retrieval-colpali/main.py
=> (colpali) do not store to disk

visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/frontend/layout.py, visual-retrieval-colpali/output.css
=> Fix negative margin

visual-retrieval-colpali/.env.example, visual-retrieval-colpali/backend/vespa_app.py
=> optional mtls

visual-retrieval-colpali/backend/vespa_app.py
=> print mtls or token

visual-retrieval-colpali/main.py
makes the id be unique every time.
Seem to fix the variations in latency locally. 🫰
=> unique ids every time

visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/backend/vespa_app.py
Does not raise Exception, and is returned so that frontend responds politely with 
_No results found for your query._
=> handle empty results in backend

visual-retrieval-colpali/prepare_feed_deploy.py
=> rank profiles without sim map

visual-retrieval-colpali/.gitignore, visual-retrieval-colpali/backend/colpali.py, visual-retrieval-colpali/backend/modelmanager.py, visual-retrieval-colpali/backend/vespa_app.py, visual-retrieval-colpali/frontend/app.py, visual-retrieval-colpali/main.py
This should fix the missing sim maps after switching to unique id. 
Please confirm that latency issue also is still good by running locally.
=> (colpalidemo) fix sim maps

visual-retrieval-colpali/backend/stopwords.py, visual-retrieval-colpali/backend/vespa_app.py, visual-retrieval-colpali/pyproject.toml, visual-retrieval-colpali/uv.lock
=> remove stopwords

.gitignore, visual-retrieval-colpali/.gitignore, visual-retrieval-colpali/prepare_feed_deploy.py, visual-retrieval-colpali/vespa_feed_to_hf_dataset.py
Feeding of full dataset in progress.   
Have URL's and key/cert available on demand 🔒
=> (colpalidemo) vespa feed to hf dataset.py

visual-retrieval-colpali/README.md, visual-retrieval-colpali/requirements.txt
This is the one hf uses by default.
=> (colpalidemo) compile to requirements.txt

billion-scale-image-search/README.md, billion-scale-vector-search/README.md, commerce-product-ranking/README.md, custom-embeddings/README.md, examples/document-processing/README.md, examples/generic-request-processing/README.md, examples/http-api-using-request-handlers-and-processors/README.md, examples/multiple-bundles/README.md, examples/operations/multinode-HA/README.md, examples/part-purchases-demo/README.md, examples/predicate-fields/README.md, incremental-search/search-as-you-type/README.md, incremental-search/search-suggestions/README.md, model-inference/README.md, msmarco-ranking/README.md, multi-vector-indexing/README.md, multilingual-search/README.md, text-image-search/README.md, transformers/README.md, use-case-shopping/README.md, vector-streaming-search/README.md
=> Add alternative podman command for memory info

examples/operations/multinode-HA/README.md
- there might be more of these, I did not check
=> don't run the mem check

visual-retrieval-colpali/README.md
This is where a user should pick up after finishing the notebook. 
Adapted it to reflect this. 
Please step through and verify. 🙏
=> (colpalidemo) Improve README

visual-retrieval-colpali/src/frontend/app.py
We can merge this just to have some queries that all work well, but I think we should iterate more later
- too many of them have a year
- one is way too long
- we may want to separate the "visual" queries from the more "serious" textual ones
=> sample queries

visual-retrieval-colpali/src/backend/colpali.py
Reduces discrepancy between Apple (mps) and HF (Cuda). 
Still some minor discrepancies though, but we'll have to live with that.
=> (colpalidemo) fix to bfloat16

visual-retrieval-colpali/prepare_feed_deploy.py
=> (colpalidemo) fieldset fix

visual-retrieval-colpali/prepare_feed_deploy.py
This made some of the urls not match the actual doc. 
Have generated and fed the updated full dataset. (Can AirDrop).
=> (colpalidemo) do not download non pdf links

commerce-product-ranking/notebooks/Train-lightgbm.ipynb
=> lightgbm typo

README.md
modified from the readme in the other repo
=> Friendlier and more helpful intro

examples/lucene-linguistics/README.md
=> don't specify fixed, too old Vespa version

text-search/README.md, text-search/ext/logstash.conf
For the text-search sample app.
=> instructions to feed MSMARCO data with Logstash

text-search/README.md, use-case-shopping/README.md, use-case-shopping/logstash.conf
It's not *that* useful for the demo itself, as one will still need to feed suggestions separately (suggestions conversion needs Spacy). And suggestions also need items to be converted.
But I think it's a nice demo of how one could use Logstash as an ETL tool for this kind of data.
=> Logstash example for use-case-shopping

examples/training-artifacts/101/ch2/README.md, examples/training-artifacts/101/ch2/ecommerce/ext/logstash.conf
This is a pretty straightforward demo on how to use Logstash for a simple CSV file.
Simple, but with a quirk: some "rows" are multi-line :)
=> logstash config and README for the training Ecommerce app

examples/part-purchases-demo/README.md, examples/training-artifacts/101/ch2/ecommerce/ext/logstash.conf, examples/training-artifacts/101/ch3/README.md, examples/training-artifacts/101/ch3/logstash.conf, examples/training-artifacts/101/ch3/part-purchase/validation-overrides.xml
We actually have this app in both places - the original parts-purchase-demo and in the grouping chapter (ch3) of Vespa 101 training artifacts. `logstash.conf` lives in the training artifacts (where there are some more products) and we reference it from both READMEs.
=> logstash config and README for parts-purchase-demo

README.md
- Add video search, move Colpali to Visual Search
=> reorganize

msmarco-ranking/README.md
@lperry25  can this be a useable format to extract data fro the console view?
=> Reformat for summary and feature extraction

text-image-search/README.md
@lperry25 here's another one to integrate
=> Format for console extraction

README.md
- ... so I find this easily next time :-)
=> mention elementSimilarity

examples/part-purchases-demo/README.md, examples/training-artifacts/101/ch2/README.md, examples/training-artifacts/101/ch3/README.md, text-search/README.md, use-case-shopping/README.md
Serves as additional resources.
=> Link Logstash recipes blog post from Logstash-related sections

README.md
=> Improve e-commerce section

examples/part-purchases-demo/schemas/purchase.sd
=> add map field

use-case-shopping/src/main/application/services.xml, use-case-shopping/src/main/resources/templates/header.html.template
- probably required now as the docker container binds 127.0.0.1:8080:8080 explicitly
- fix logo while at it
=> Make local serving work again

use-case-shopping/README.md
- This app can be _deployed_ to Vespa Cloud, but the site serving does not work due to the implementation
=> deploy local only

.github/workflows/link-checker.yml
=> ignore link

examples/operations/multinode-HA/README.md, examples/operations/multinode-HA/gke/README.md, examples/operations/multinode/README.md, text-search/README.md, text-search/dataset/.gitkeep, text-search/python/convert-to-vespa-format.py, text-search/scripts/build.sh, text-search/scripts/convert-msmarco.sh
Update documentation to fix [Verify Guides (Main)](https://github.com/vespa-engine/sample-apps/actions/workflows/verify-guides-main.yml?query=branch%3Amaster)
Use the new directory structure defined in https://github.com/vespa-engine/sample-apps/pull/1670
=> fix: update README and scripts

album-recommendation-java/src/main/application/services.xml, album-recommendation-java/src/main/java/ai/vespa/example/album/GroupingSearcher.java, album-recommendation-java/src/test/java/ai/vespa/example/album/GroupingSearcherTest.java
A new GroupingSearcher and tests were added.
There will be some comments soon.
=> Add GroupingSearcher example

field-generator/README.md
=> Updated generate app verification

field-generator/README.md, field-generator/services.xml
=> Using url instead of model id, extended timeout

retrieval-augmented-generation/README.md
=> add structured output example

.github/workflows/link-checker.yml
=> run at different time from others

_config.yml, _paragraphs_config.yml, _suggestions_config.yml
=> harmonize doc feed endpoints

examples/lucene-linguistics/simple-korean/README.md, examples/lucene-linguistics/simple-korean/pom.xml, examples/lucene-linguistics/simple-korean/src/main/application/schemas/simple.sd, examples/lucene-linguistics/simple-korean/src/main/application/services.xml
=> add simple example of using KoreanTokenizer from lucene-linguistics

rag-blueprint/README.md
=> Added Vespa Cloud account to Prerequisites in Readme

text-image-search/src/main/java/ai/vespa/example/BPETokenizer.java, text-image-search/src/test/application/tests/system-test/image-search-system-test.json
=> BPETokenizer: trim tokens when text exceeds contextLength

.github/workflows/update-cloud-samples.yml
=> invert our check for master branch for dryrun and echo since empty string is falsy

visual-retrieval-colpali/prepare_feed_deploy.py
=> update gemini model

examples/ecommerce-user-preferences/README.md
- Corrected punctuation and added installation step for Logstash plugin.
=> vespa_feed install
